---
title: "Wrap-up: Communication and Ethics"
author: "K Arnold"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    self_contained: FALSE
    lib_dir: libs
    nature:
      ratio: "16:9"
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE, message=FALSE}
source("../slides-common.R")
slideSetup()
knitr::opts_chunk$set(echo = TRUE)
```

---

class: center, middle

## Making a Data-Driven Argument

---

### Make a point

.pull-left[
**Report A**

MAIN POINT

* Supporting chart 1
* Supporting table 2
* Supporting model 3

Discussion about how each supports main point
]

.pull-right[
**Report B**

* Chart 1
* Table 2
* Model 3
* Chart 4
* Table 5
* Chart 6
* Model 7
* Chart 12
* Table 25
]

---

### Tell a Story

* Chart 1
* Therefore, chart 2
* BUT, chart 3

[but-therefore](https://www.youtube.com/watch?v=vGUNqq3jVLg)

---

### Anchor conclusions in data

.pull-left[
* The units are probably seconds<br><br>
* The fit looks good<br><br>
* This was surprising
]

--

.pull-right[
* because the median, 600, would be 10 minutes
* because the mean error of $15 is less than 0.1% of the price
* because I expected that people would leave higher ratings on products they enjoyed more
]

---

## Tools for Communication

* Slides
  * Xaringan
* RStudio Connect
* GitHub Pages
* Shiny Apps

---

### Example: [Shiny](https://shiny.rstudio.com/) Apps

<https://shiny.rstudio.com/gallery/>

* [Engineering Production-Grade Shiny Apps](https://engineering-shiny.org/)

---

class: center, middle

## Final Thoughts on Data + Justice

With enormous thanks to:

Tim Keller, [A Biblical Critique of Secular Justice and Critical Theory](https://quarterly.gospelinlife.com/a-biblical-critique-of-secular-justice-and-critical-theory/)

---

### Community

> The righteous (saddiq) are willing to disadvantage themselves to advantage the community; the wicked are willing to disadvantage the community to advantage themselves.

So:

* privacy
* integrity in data collection, analysis, reporting, communication

---

### Equity: Everyone must be treated equally and with dignity.

* *direct* impact
  * fair risk assessment (see Discussion and COMPAS)
  * fair resource allocation
  * fair surveillance (don't hyper-surveil the poor etc.)
* *indirect* impact:
  * don't show ads for criminal background checks more often for Black names
  * don't tolerate higher speech reco error rates for minorities
  * show a representative diversity of age/gender/race/... in image searches

---

### Should we even be predicting peoples' lives?

* Risk assessment for criminality, loan approval, etc. requires predicting
  peoples' future actions and situations
* These predictions might be terribly inaccurate. *Should we be trying at all*?

Salganik et al, [**Measuring the predictability of life outcomes with a scientific mass collaboration**](https://www.pnas.org/content/117/15/8398.short). PNAS, April 2020

> Despite using a rich dataset and applying machine-learning methods optimized for prediction, the best predictions were not very accurate and were only slightly better than those from a simple benchmark model.

---

### Corporate responsibility: I am sometimes responsible for and involved in other people’s sins.

* Even if *I* intend no prejudice, my *algorithm* could be prejudiced because of training data.
* Even if my work is honest, I could be supporting a company that exploits other
  workers directly or rely on conflict minerals and [child labor](https://www.bbc.com/news/world-africa-50812616)
* Environmental responsibility is both individual and collective

???

http://opiniojuris.org/2020/01/13/the-mighty-apple-google-tesla-dell-and-microsoft-in-the-dock-a-look-at-the-child-labour-lawsuit/

---

### Individual responsibility: I am finally responsible for all my sins, but not for all my outcomes.

* I must do what's right, whether or not my company's policies require it.
* When something isn't right, I need to say something even if it risks my job.

---

### Advocacy: We must have special concern for the poor and the marginalized.

* By **listening to** and **amplifying**, not **speaking for**.
* e.g., beware of doing "parachute research" or de-contextualized "Data for Good"

---

### Incarnation

.scripture[
```
In your relationships with one another, have the same mindset as Christ Jesus:
Who, being in very nature God,
    did not consider equality with God something to be used to his own advantage;
rather, he made himself nothing
    by taking the very nature of a servant,
    being made in human likeness.
And being found in appearance as a man,
    he humbled himself
    by becoming obedient to death—
        even death on a cross!
```
.ref[Philippians 2:5-8, NIV]
]


---

## Who I'm Reading / Following: Data Ethics

* AI Now Institute
* Data and Society
* [AlgorithmWatch](https://algorithmwatch.org/en/)
* [Harvard BKC](https://twitter.com/BKCHarvard)
* Data Feminism
* ACM Conference on Fairness, Accountability, and Transparency ([FAccT](https://facctconference.org/))

People:

* [Cassie Kozyrkov](https://decision.substack.com/) ([@quaesita](https://twitter.com/quaesita))
* [Timnit Gebru](https://twitter.com/timnitGebru)
* [Rediet Abebe](https://twitter.com/red_abebe)
* [J. Nathan Matias](https://twitter.com/natematias)
* [Joy Buolamwini](https://twitter.com/jovialjoy)

---

## Who I'm Reading / Following: Tech

* [RStudio AI blog](https://blogs.rstudio.com/ai/)
* [tidyverse blog](https://www.tidyverse.org/blog/)
* [RWeekly](https://rweekly.org/)
* [distill.pub](https://distill.pub/)
* [Harvard Data Science Review](https://hdsr.mitpress.mit.edu/)

---

## "What can I do?"

* Choose jobs carefully ([How to Interview a Tech Company](https://medium.com/@AINowInstitute/how-to-interview-a-tech-company-d4cc74b436e9))
* Listen a lot. To diverse opinions.
* Keep in touch.
