---
title: "Exercise 12: Logistic Regression, Regularization, and Cross-Validation"
execute: 
  echo: true
---

In this exercise, we'll practice *classification* using a logistic regression model. Since this model is prone to overfit, we'll learn how to tame its excesses with *regularization*, and estimate how well it will generalize to new data using *cross-validation*.

Completing this exercise will help you be able to:

- Fit a logistic regression model to a dataset using scikit-learn
- Use regularization to prevent overfitting
- Use cross-validation to estimate how well a model will generalize to new data

Along the way, we'll also see a technique for handling missing data, and get more practice with how to build pipelines in scikit-learn.

Code will be provided for this exercise. You should retype the code on your own and try to understand what each part does. There will also be some conceptual questions for you to answer.

## Getting Started

We'll use a dataset of who survived the Titanic shipwreck. To help make the point of this exercise more clear, we'll also augment the dataset with some irrelevant (noise) features. We'll keep the original goal, though: to predict whether a passenger survived or not.[^source]

::: {.column-margin}
This task is a classic in machine learning, but I've never seen anyone mention how fake this prediction task is! There is no real-world scenario where you get to see whether some passengers survived and some didn't, and then you have to predict whether other passengers survived or not. When you're doing projects, *please* think about whether the task you're trying to solve is (a) a task that anyone would actually care about and (b) a task that's doable using data that you'd actually have access to.
:::

[^source]: This exercise is based in part on [this example from the sklearn docs](https://scikit-learn.org/stable/auto_examples/compose/plot_column_transformer_mixed_types.html).

Here are the imports you'll need.

```{python}
#| echo: fenced
import pandas as pd
import numpy as np

from sklearn.compose import make_column_transformer
from sklearn.datasets import fetch_openml, load_breast_cancer
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.linear_model import LogisticRegression, LogisticRegressionCV
from sklearn.model_selection import train_test_split, LeaveOneOut, cross_val_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.metrics import accuracy_score

import plotly.express as px
```

We'll load the data from a site called [OpenML](https://www.openml.org/). OpenML is a repository of datasets that are useful for machine learning. Specifically we'll load the [Titanic dataset](https://www.openml.org/d/40945). This dataset contains information about passengers on the Titanic, including whether they survived or not. The [Kaggle page for this dataset](https://www.kaggle.com/c/titanic/data) has more information about the features.

```{python}
#| echo: fenced
titanic_all = fetch_openml(
    data_id=40945, as_frame=True, parser="pandas"
)
titanic = titanic_all.frame
```

Now we'll add some noise features. Just copy-paste this code; don't worry about how it works.
    
```{python}
rng = np.random.RandomState(0)
n_samples = titanic.shape[0]
n_features = 500
noise_feature_names = [f"noise_{i}" for i in range(n_features)]
noise_features = pd.DataFrame(
    rng.normal(size=(n_samples, n_features)),
    columns=noise_feature_names
)
titanic = pd.concat([titanic, noise_features], axis=1)
titanic.info()
```

We'll use two numeric features (in addition to the noise features):

- `age`: the age of the passenger
- `fare`: the fare paid by the passenger

And three categorical features:

- `embarked`: the port where the passenger embarked (`C` = Cherbourg, `Q` = Queenstown, `S` = Southampton)
- `sex`
- `pclass`: the passenger class (`1` = first class, `2` = second class, `3` = third class)

Note that `pclass` is encoded as a number, but it's really a categorical feature. We'll treat it as categorical.

```{python}
#| echo: fenced
# Select the features and target
target_column = "survived"
numeric_features = ["age", "fare"] + noise_feature_names
categorical_features = ["embarked", "sex", "pclass"]
feature_columns = numeric_features + categorical_features
```

Let's hold out a test set. We'll use a large test set so that our estimates of generalization error have less variance.

```{python}
#| echo: fenced
titanic_train, titanic_test = train_test_split(
    titanic, test_size=.5, random_state=0
)
print(f"Training set size: {titanic_train.shape[0]}")
print(f"Test set size: {titanic_test.shape[0]}")
```

The numeric features will need some preprocessing. We'll first scale them to be zero mean and unit variance, and then impute missing values. Note: at this step we're just defining what processing will happen; the actual processing will be done later when we fit the pipeline.

```{python}
#| echo: fenced
numeric_transformer = make_pipeline(
    StandardScaler(),
    SimpleImputer(strategy="median")
)
```

**Pause to think**:

- What is `strategy="median"` doing? What alternative strategies could we use for imputing missing values? Do you think the median would be a good guess for the missing values?
- Why do we need to impute missing values *after* scaling the features? What would happen if we did it the other way around?

The categorical features need to be one-hot-encoded.

```{python}
#| echo: fenced
categorical_transformer = make_pipeline(
    SimpleImputer(strategy="most_frequent"),
    OneHotEncoder(handle_unknown="ignore", sparse_output=False)
)
```

**Pause to think**: How many columns will the categorical transformer produce? What will each column represent? Write a brief explanation.

We can combine the numeric and categorical transformers into a single transformer that will apply each one to the appropriate columns.

```{python}
#| echo: fenced
preprocessor = make_column_transformer(
    (numeric_transformer, numeric_features),
    (categorical_transformer, categorical_features)
).set_output(transform='pandas')
```

Let's show an example of what this preprocessor will do to our data. Check your results from above.

```{python}
example_preprocessed_data = preprocessor.fit_transform(titanic_train[feature_columns])
example_preprocessed_data.info()
example_preprocessed_data.head()
```

Notice that there are no missing values and that there are separate columns for each of the possible values of the categorical variables.

Now we can put all of those elements together to train a basic logistic regression model.

```{python}
#| echo: fenced
model = make_pipeline(
    preprocessor,
    LogisticRegression(penalty=None)
)
```

**Your turn**: fit and evaluate this model (using `model.fit(...)`). What is the accuracy on the training set? What is the accuracy on the test set?

```{python}
#| echo: false
model.fit(X=titanic_train[feature_columns], y=titanic_train[target_column])
titanic_train['prediction'] = model.predict(titanic_train[feature_columns])
titanic_test['prediction'] = model.predict(titanic_test[feature_columns])
```

```{python}
#| echo: false
accuracy_train = (titanic_train['prediction'] == titanic_train[target_column]).mean()
accuracy_test = (titanic_test['prediction'] == titanic_test[target_column]).mean()
print(f"Accuracy on training set: {accuracy_train:.3f}")
print(f"Accuracy on test set: {accuracy_test:.3f}")
```

What do you notice about the accuracy of the model on the training set vs the test set?

## Regularization

The model was able to get a perfect score on the training set. But to do that, it used some of the noise features, which clearly will not generalize to new data. We can see this by looking at the coefficients of the model:

```{python}
def get_coefs_df(model, feature_names):
    logreg = model.named_steps['logisticregression']
    assert logreg.coef_.shape[0] == 1
    assert logreg.coef_.shape[1] == len(feature_names)
    coefs_df = pd.DataFrame(dict(
        name=feature_names,
        coef=logreg.coef_[0]
    ))
    coefs_df['abs_coef'] = coefs_df['coef'].abs()
    return coefs_df.sort_values('abs_coef', ascending=False)

coefs_df = get_coefs_df(model, example_preprocessed_data.columns)
coefs_df.head(10)
```

```{python}
coefs_df['is_noise'] = coefs_df['name'].str.contains('noise')
print("Total noise coefficients: {:.2f}".format(
    coefs_df.query('is_noise')['coef'].abs().sum())
)
```

If we could get the model to put less weight on the noise features, it might generalize better. But in a real example, we don't know which features are noise. And some features may be partly noise, partly signal. So we can't just remove the noise features.

Instead, we can use *regularization* to encourage the model to put less weight on *any* individual feature. The hope is that this will encourage the model to put more weight on the features that are signal, and less weight on the features that are noise.


```{python}
#| echo: fenced
model = make_pipeline(
    preprocessor,
    LogisticRegression(C=1e-1, penalty='l1', solver='liblinear')
).fit(
    X=titanic_train[feature_columns],
    y=titanic_train[target_column]
)
print("Accuracy on training set:", model.score(
    X=titanic_train[feature_columns],
    y=titanic_train[target_column]
))
print("Accuracy on test set:", model.score(
    X=titanic_test[feature_columns],
    y=titanic_test[target_column]
))
```

```{python}
coefs_df = get_coefs_df(model, example_preprocessed_data.columns)
coefs_df.head(10)
```

```{python}
coefs_df['is_noise'] = coefs_df['name'].str.contains('noise')
print("Total weight on noise coefficients: {:.2f}".format(
    coefs_df.query('is_noise')['coef'].abs().sum())
)
```

**Your turn**: what do you notice about the model's accuracy scores now? What do you notice about the coefficients?

**Your turn**: Try adjusting the value of `C` in the model. Answer:

- How does the training accuracy change as `C` changes? 
- What value of `C` gives the best training accuracy?
- How does the test accuracy change as `C` changes?
- What value of `C` gives the best test accuracy?
- How does the amount of weight that the model puts on the noise features change as `C` changes?
- Does a high value of `C` seem to correspond to regularizing a *lot* or a *little*?

This plot might help you answer some of those questions:

```{python}
# Make a plot of train and test accuracy vs C
C_values_to_try = [1e-4, 1e-3, 1e-2, 1e-1, 1, 10, 100]
train_accuracies = []
test_accuracies = []
for C in C_values_to_try:
    model = make_pipeline(
        preprocessor,
        LogisticRegression(C=C, penalty='l1', solver='liblinear')
    ).fit(
        X=titanic_train[feature_columns],
        y=titanic_train[target_column]
    )
    train_accuracies.append(model.score(
        X=titanic_train[feature_columns],
        y=titanic_train[target_column]
    ))
    test_accuracies.append(model.score(
        X=titanic_test[feature_columns],
        y=titanic_test[target_column]
    ))
accuracies_df = pd.DataFrame(dict(
    C=C_values_to_try,
    train_accuracy=train_accuracies,
    test_accuracy=test_accuracies
)).melt(id_vars='C', var_name='dataset', value_name='accuracy')
```

```{python}
px.line(accuracies_df, x='C', y='accuracy', color='dataset', log_x=True)
```

## Cross-Validation

We've seen that regularization can help prevent overfitting. But how do we know how much regularization to use? We could try different values of the regularization parameter `C` and see which one gives the best accuracy on the test set. But that would be a waste of data. We'd be using the test set to choose the model, which would make it less reliable as an estimate of generalization error.

Instead, we can use *cross-validation* to estimate how well the model will generalize to new data. The idea is to hold out one of the data points, train the model on the rest, and then see how well it predicts the held-out data point. We can repeat this process for each data point, and then average the scores to get an estimate of how well the model will generalize.

Buuut... that requires training the model as many times as there are data points. That's a lot of training! (I tried it and got tired of waiting.) So, instead of holding out one data point at a time, we can hold out a bunch of points at a time. These groups of points are called *folds*. We then test the model on each fold, using the other folds as the training set. We can then average the scores on each fold to get an estimate of how well the model will generalize.

**Your turn**: If we have 100 data points and we use 10-fold cross-validation, how many data points will be in each fold? How many times will we train a model? How big will the training set be each time? How big will the test set be each time?

```{python}
#| echo: fenced
C_values_to_try = [1e-4, 1e-3, 1e-2, 1e-1, 1, 10, 100]
model = make_pipeline(
    preprocessor,
    LogisticRegressionCV(Cs=C_values_to_try, penalty='l1', solver='liblinear', cv=5)
).fit(
    X=titanic_train[feature_columns],
    y=titanic_train[target_column]
)
```

The `LogisticRegressionCV` class will try each value of `C` in `C_values_to_try`, and use cross-validation to estimate how well the model will generalize. Let's see what the cross validation process estimated for each value of `C`.

```{python}
# ignore the ['1']; it's an implementation detail that matters if we have multiple classes.
estimated_scores = model.named_steps['logisticregressioncv'].scores_['1']
# estimated_scores is (n_folds, n_C_values)
estimated_scores_df = pd.DataFrame(
    estimated_scores,
    columns=C_values_to_try
).melt(var_name="C", value_name="score")
```

```{python}
px.box(estimated_scores_df, x="C", y="score", title="Cross-validation scores", log_x=True)
```

The cross-validation process estimated that the best value of `C` is:

```{python}
model.named_steps['logisticregressioncv'].C_
```

It will then choose the value of `C` that gives the best cross-validation score, and train a model using that value of `C` on the entire training set. We can use that model to make predictions on the test set.

```{python}
print("Accuracy on training set:", model.score(
    X=titanic_train[feature_columns],
    y=titanic_train[target_column]
))
print("Accuracy on test set:", model.score(
    X=titanic_test[feature_columns],
    y=titanic_test[target_column]
))
```

Your turn: How did that test set accuracy compare with the accuracy estimated by cross validation?

