---
title: "12: Validation"
---

# Objectives


# Reading

- [A debugging manifesto](https://jvns.ca/blog/2022/12/08/a-debugging-manifesto/)
    - She runs a great blog. See [Making Hard Things Easy](https://jvns.ca/blog/2023/10/06/new-talk--making-hard-things-easy/) for another example.
- More interactive articles written by Amazon's Machine Learning team:
    - [Logistic Regression](https://mlu-explain.github.io/logistic-regression/)
    - [Cross Validation](https://mlu-explain.github.io/cross-validation/)
- Browse the sklearn documentation:
    - [Cross Validation in the User Guide](https://scikit-learn.org/stable/modules/cross_validation.html#cross-validation)
    - [sklearn.model_selection.train_test_split](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html)
    - [sklearn.model_selection.cross_val_score](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html)

Additional perspectival readings are on the Perusall assignment. Don't try to read all of them, just pick one or two.

In case Perusall isn't working, here's the direct links:

- [Moneyball: the Oakland A's and the transformation of baseball data - Marketplace](https://www.marketplace.org/shows/marketplace-tech/moneyball-the-oakland-as-and-the-transformation-of-baseball-data/)
- [The copyright fight over authors and OpenAI’s ChatGPT - Vox](https://www.vox.com/future-perfect/2023/10/25/23930683/openai-chatgpt-george-rr-martin-john-grisham-ai-safety-artificial-intelligence-copyright-law-chatbot) or [Authors sue OpenAI for using copyrighted material](https://www.npr.org/2023/11/10/1197954613/openai-chatgpt-author-lawsuit-preston-martin-franzen-picoult)

## Optional Activities

- [Equality of Odds](https://mlu-explain.github.io/equality-of-odds/)
- a fun classifier example: [Blabrecs](https://mkremins.github.io/publications/Blabrecs_NeurIPS2023.pdf)
