---
title: "12.1 Linear Regression and Classification"
icon: "file-slides"
format:
  revealjs:
    theme: [default, slides.scss]
    scrollable: true
    revealjs-plugins:
      - "fix-plotly-size"
execute: 
  echo: true
---

```{python}
import pandas as pd
import numpy as np
from sklearn.compose import make_column_transformer, make_column_selector
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import accuracy_score, mean_absolute_error, mean_absolute_percentage_error
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split
import plotly.express as px
import matplotlib.pyplot as plt
import plotly.io as pio
pio.templates.default = "plotly_white"
pd.options.plotting.backend = "plotly"
```

## Objectives

- explain how scaling features affects a linear regression coefficients
- preprocess data to prepare it for modeling
- explain how to use a linear model to make classifications

## Example: Ames Housing again

Data link: [ames_home_sales.csv](https://calvin-data-science.github.io/data202/data/ames/ames_home_sales.csv)

```{python}
#| echo: false
data = pd.read_csv("../../static/data/ames/ames_home_sales.csv")
```

```python
data = pd.read_csv("data/ames_home_sales.csv")
```


```{python}
data['sale_price'] = data.eval("Sale_Price / 1000")
ames = data.query('Gr_Liv_Area < 4000 and Sale_Condition == "Normal"')
```


```{python}
ames_train, ames_test = train_test_split(ames, random_state=42, test_size=0.2)
print(f"Training set size: {len(ames_train)} homes")
print(f"Test set size: {len(ames_test)} homes")
```

```{python}
def evaluate(y_true, y_pred):
    return pd.Series({
        'MAE': mean_absolute_error(y_true, y_pred),
        'MAPE': mean_absolute_percentage_error(y_true, y_pred),
    })
```

## Fit linreg with all numeric features {.smaller}

```{python}
target_column = 'sale_price'
feature_columns = [column for column in ames.columns if column != target_column]
print(f"Number of features: {len(feature_columns)}")
```

```{python}
transformer = make_column_transformer(
    ('passthrough', make_column_selector(dtype_include=np.number)),
    verbose_feature_names_out=False
).set_output(transform='pandas')
example_transformed_output = transformer.fit_transform(ames_train[feature_columns])
example_transformed_output.head()
```

```{python}
linreg = LinearRegression()
pipeline = (
    make_pipeline(transformer, linreg)
    .fit(
        X=ames_train[feature_columns],
        y=ames_train[target_column]
    )
)
evaluate(ames_train[target_column], pipeline.predict(ames_train[feature_columns]))
```

```{python}
evaluate(ames_test[target_column], pipeline.predict(ames_test[feature_columns]))
```

This model has a big problem---can you figure out what it is?

## Coefficients

```{python}
pd.DataFrame({
    'coefficient': linreg.coef_,
    'feature': example_transformed_output.columns
}).sort_values('coefficient').style.hide(axis='index')
```

## Fixed Model

```{python}
#| code-line-numbers: "2"
data['sale_price'] = data.eval("Sale_Price / 1000")
del data['Sale_Price']
ames = data.query('Gr_Liv_Area < 4000 and Sale_Condition == "Normal"')
```

```{python}
ames_train, ames_test = train_test_split(ames, random_state=42, test_size=0.2)
print(f"Training set size: {len(ames_train)} homes")
print(f"Test set size: {len(ames_test)} homes")
```


```{python}
target_column = 'sale_price'
feature_columns = [column for column in ames.columns if column != target_column]
print(f"Number of features: {len(feature_columns)}")
```


```{python}
example_transformed_output = transformer.fit_transform(ames_train[feature_columns])
example_transformed_output.head()
```

```{python}
pipeline = (
    make_pipeline(transformer, linreg)
    .fit(
        X=ames_train[feature_columns],
        y=ames_train[target_column]
    )
)
evaluate(ames_train[target_column], pipeline.predict(ames_train[feature_columns]))
```

```{python}
evaluate(ames_test[target_column], pipeline.predict(ames_test[feature_columns]))
```


```{python}
pd.DataFrame({
    'coefficient': linreg.coef_,
    'feature': example_transformed_output.columns
}).sort_values('coefficient').style.hide(axis='index')
```

## Aside: some EDA

How does location affect price?

```{python}
px.scatter(ames_train, x="Longitude", y="Latitude", color="sale_price", opacity=0.5)
```

We see some expensive homes in the northwest.

```{python}
(
    px.scatter(ames_train, x="Gr_Liv_Area", y="sale_price", trendline="ols")
    .update_traces(marker_opacity=0.5)
)
```

```{python}
(
    px.scatter(ames_train, x="Lot_Area", y="sale_price", trendline="ols")
    .update_traces(marker_size=2)
)
```

## Scaling

- Each coefficient: how much the model's prediction changes when adding 1 to that feature.
- But the features are on different scales
  - e.g. `Lot_Area` is in square feet: 1 square foot shouldn't make much difference.
  - but 1 degree of `Latitude` is a huge difference
  - So the coefficient for `Lot_Area` would have to be much larger to have the same effect
- **Scaling** the features makes the coefficient value indicate its importance

::: aside
This silde written with a lot of help from GitHub Copilot
:::

## Standard Scaler

- [`StandardScalar`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html) subtracts the mean and divides by the standard deviation
- This makes the mean 0 and the standard deviation 1
- So the coefficients reflect how much impact a one-standard-deviation change in the feature has on the model

::: {.columns}
::: {.column width="50%"}

Before scaling:
```{python}
px.histogram(ames_train, x="Lot_Area")
```
:::

::: {.column width="50%"}

After scaling:
```{python}
px.histogram(StandardScaler().fit_transform(ames_train[["Lot_Area"]]))
```
:::
:::


## Fit linreg with scaled features

```{python}
transformer = make_column_transformer(
    (StandardScaler(), make_column_selector(dtype_include=np.number)),
    verbose_feature_names_out=False
).set_output(transform='pandas')
example_transformed_output = transformer.fit_transform(ames_train[feature_columns])
example_transformed_output.describe()
```

Notice that the mean is 0 and the standard deviation is 1.

```{python}
pipeline = (
    make_pipeline(transformer, linreg)
    .fit(
        X=ames_train[feature_columns],
        y=ames_train[target_column]
    )
)
evaluate(ames_train[target_column], pipeline.predict(ames_train[feature_columns]))
```

Notice: error didn't change.

```{python}
evaluate(ames_test[target_column], pipeline.predict(ames_test[feature_columns]))
```

## Coefficients

```{python}
pd.DataFrame({
    'coefficient': linreg.coef_,
    'feature': example_transformed_output.columns
}).sort_values('coefficient').style.hide(axis='index')
```

Each coef means: how much the model's prediction changes when adding 1 standard deviation to that feature.

## Hyperparameters {.smaller}

- **Parameters** are the parts of the model that are learned from data
  - coefficients in a linear regression, splits in a decision tree, ...
- **Hyperparameters** are the parts of the model that are set before training
  - depth of a decision tree, which variables are used, how they are transformed, ...
  - *not* learned directly from data
  - but modeler can choose them based on data

# Linear Classifiers

*"Logistic Regression"*

## Load up a familiar example: blood test for autism

```{python}
autism = pd.read_csv("data/autism.csv", skiprows=[1])
```

- Last time we fit a decision tree. But that assumed hard cut-offs for each feature. 
- Linear models could say: each additional percentage oxidized (or whatever) leads to a 0.1% increase in risk of autism.

*The real world isn't black and white; linear models can help model the gray areas.*

## Set up as before:

```{python}
autism_train, autism_test = train_test_split(autism, random_state=42, test_size=0.25)

feature_columns = list(autism.columns[1:-1])
target_column = "Group"

positive_outcome = "ASD"
negative_outcome = "NEU"
```

## What it looks like

```{python}
model = make_pipeline(
    StandardScaler(),
    LogisticRegression(C=4e-2, penalty='l1', solver='liblinear')
).fit(
    X=autism_train[feature_columns],
    y=autism_train[target_column] == positive_outcome
)
pd.DataFrame({
    'coeficients': model.named_steps["logisticregression"].coef_[0],
    'feature': feature_columns}
    ).sort_values("coeficients").query("coeficients != 0").plot.scatter(x='coeficients', y='feature')
```

## How this classifier makes predictions

First, it predicts a *risk score* (negative = low risk, positive = high risk).

```{python}
print(f"y = {model.named_steps['logisticregression'].intercept_[0]:.2f}", end="")
for coef, feature in zip(model.named_steps["logisticregression"].coef_[0], feature_columns):
    if coef != 0:
        print(f"+ {coef:.2f} * {feature}", end="")
```

Note: these are the coefficients of the *scaled* features.

Example for the first row of the test set:

```{python}
example_risk_score = model.decision_function(autism_test[feature_columns].iloc[[0]])
example_risk_score
```

Then it uses the *logistic* function to turn risk score into probability:

```{python}
def logistic(x):
    return 1 / (1 + np.exp(-x))
# show the logistic function. draw a line at 0.5
x = np.linspace(-10, 10, 100)
(
    px.line(x=x, y=logistic(x))
    .add_hline(y=0.5)
    .update_layout(xaxis_title="risk score", yaxis_title="probability")
)
```

For the example above:

```{python}
logistic(example_risk_score)
```

```{python}
model.predict_proba(autism_test[feature_columns].iloc[[0]])
```

## Intuition: *Risk*

- First, linear model predicts a *risk score* (negative = low risk, positive = high risk).
  - Technically: *log* of the *odds*: log(prob of *yes* / prob of *no*)
  - Odds of 1: equal chance of *yes* and *no*; odds of 2: twice as likely to be *yes* as *no*
- Then, *logistic* function turns risk score into probability

Other examples:

- Risk of a customer churning
- Risk of a transaction being fraudulent
- Chance of one team winning: difference in skill scores (Elo)

## Intuition: *Logistic* function

- **Monotonic**: higher risk score = higher probability
- but non-linear: as risk score increases, probability increases more slowly
    - twice the risk score does not mean twice the probability
    - when probability is near 0.5, a small change in risk score can make a big change in probability (tipping between a yes or no decision, so it's important to get it right)
    - near 1, a small change in risk score doesn't change probability much (already pretty sure of the answer)

## Hyperparameters: regularization

- Notice that we had many possible features, but only a few coefficients are non-zero
- We used a *penalty* to encourage the model to use fewer features
- Without the penalty, we would have a coefficient for each feature

```{python}
#| code-line-numbers: "3"
model = make_pipeline(
    StandardScaler(),
    LogisticRegression(penalty=None)
).fit(
    X=autism_train[feature_columns],
    y=autism_train[target_column] == positive_outcome
)
pd.DataFrame({
    'coeficients': model.named_steps["logisticregression"].coef_[0],
    'feature': feature_columns}
    ).sort_values("coeficients").plot.scatter(x='coeficients', y='feature')
```

*Aside*: Perhaps `penalty=None` should have been the default; see [Scikit-learn’s Defaults are Wrong – r y x, r](https://ryxcommar.com/2019/08/30/scikit-learns-defaults-are-wrong/). Also, I don't know why `penalty=None` gives a qualitatively different set of coefs from `C=1e-16` or another tiny penalty.

## Types of Regularization

- **L1**: penalty is sum of absolute values of coefficients
  - encourages some coefficients to be exactly 0: only include features that are worth it.
- **L2**: penalty is sum of squares of coefficients
  - discourages large coefficients (no one feature can "drive" the decision)
- **Elastic Net**: combination of L1 and L2

Apply to both linear regression and linear classification ("logistic regression").

A nice visual description of the difference between L1 and L2: [Some things you (maybe) didn’t know about Linear Regression – r y x, r](https://ryxcommar.com/2019/09/06/some-things-you-maybe-didnt-know-about-linear-regression/#lassovsridge)


## But how do we pick good values for the hyperparameters?

- Penalties will make the model work *worse* on the training set, but (hopefully) better on *unseen* data.
- So we'll use a validation set to tune the hyperparameters.
- ...but how will we know how well our *tuned* model will work on actually unseen data?

# Cross-Validation

## What problem cross-validation solves?

::: copilot
- We want to use a validation set to tune hyperparameters
- But we also want to use a validation set to evaluate the model
- If we use the same validation set for both, we'll overfit to the validation set
- So we need to use *different* validation sets for tuning and evaluation
- But we don't have that many data points
- So we need to use *some* of the data for both tuning and evaluation
:::

## Leave-One-Out CV

Train on all but one data point, then evaluate on the one left out. Repeat for each data point.

```{python}
from sklearn.model_selection import LeaveOneOut, cross_val_score
scores = cross_val_score(
    model, 
    X=autism_train[feature_columns],
    y=autism_train[target_column] == positive_outcome,
    cv=LeaveOneOut())
scores
```


```{python}
scores.mean()
```

## K-Fold CV

Training a different model for each left-out datapoint can take a long time. So: **divide the data into *k* groups**, and leave one *group* out.
