---
title: "Exercise 10: Thresholds and Metrics"
execute: 
  echo: false
---

The goal of this exercise is to practice with metrics of classifier performance.

## Getting started

We'll start today with an interactive activity.

> [Attacking discrimination with smarter machine learning](http://research.google.com/bigpicture/attacking-discrimination-in-ml/)

We'll focus today on the one-group example; we'll return to the part about blue vs orange groups later.

### Explore

Spend about 10 minutes playing with the "Threshold Decision" demonstration. Discuss the following questions with your partner:

1. What are the "scores"? What real-life concept does this capture? (Do you know your score?)

2. Why might a bank want to use "score" to decide whether to grant a loan? (Why don't banks grant all loan applications? Why do they ever grant loans?)

3. What sort of predictions are being made here? What constitutes a "correct" prediction?

4. Slowly sweep the threshold from 0 to 100. On scrap paper, sketch how Correct, True Positive Rate, and Positive Rate change as the threshold changes.

### Implement

Now let's implement those metrics ourselves to check our understanding.

We've made a dataset that approximately mimics the dataset from the article. Download [people_onegroup.csv](/data/discrim/people_onegroup.csv) and put it in your `data` folder.

```{python}
#| echo: true
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.io as pio
pio.templates.default = "plotly_white"
```

```{python}
#| include: false
# On the page, run the following code in the console to generate the data.
# the first part is just the beginning of the main() function in bundle.js
js_code = """
  // Set values of true positives vs. false positives.
  var tprValue = 300;
  var fprValue = -700;

  // Parameters for main model comparison.
  var s0 = 10; // standard deviations of defaulters/payers.
  var s1 = 10;
  var d0 = 8;  // differences from means of defaulters/payers
  var d1 = 12;
  var m0 = 55; // means of overall distributions
  var m1 = 45;

  // Create items to classify: two groups with different
  // distributions of positive/negative examples.
  comparisonExample0 = new GroupModel(makeNormalItems(0, 1, 100, m0 + d0, s0)
      .concat(makeNormalItems(0, 0, 100, m0 - d0, s0)), tprValue, fprValue);
  comparisonExample1 = new GroupModel(makeNormalItems(1, 1, 100, m1 + d1, s1)
      .concat(makeNormalItems(1, 0, 100, m1 - d1, s1)), tprValue, fprValue);

  // Make a model to represent initial example of classification.
  var singleModel = new GroupModel(makeNormalItems(0, 1, 100, 60, 10)
      .concat(makeNormalItems(0, 0, 100, 40, 10)), tprValue, fprValue);

  // Make models to represent different distributions.
  var distributionExample0 = new GroupModel(makeNormalItems(0, 1, 150, 70, 7)
      .concat(makeNormalItems(0, 0, 150, 30, 7)), tprValue, fprValue);
  var distributionExample1 = new GroupModel(makeNormalItems(0, 1, 150, 60, 10)
      .concat(makeNormalItems(0, 0, 150, 40, 10)), tprValue, fprValue);


  // Need to classify to get colors to look right on histogram.
  distributionExample0.classify(0);
  distributionExample1.classify(0);

// Here's my addition
copy(JSON.stringify(singleModel.items.map(x => ({score: x.score, repay: x.value === 1}))))
"""

# that puts the following on the clipboard:
import json
data = json.loads("""[{"score":37,"repay":true},{"score":39,"repay":true},{"score":41,"repay":true},{"score":43,"repay":true},{"score":44,"repay":true},{"score":44,"repay":true},{"score":45,"repay":true},{"score":46,"repay":true},{"score":47,"repay":true},{"score":47,"repay":true},{"score":48,"repay":true},{"score":48,"repay":true},{"score":49,"repay":true},{"score":49,"repay":true},{"score":50,"repay":true},{"score":50,"repay":true},{"score":50,"repay":true},{"score":51,"repay":true},{"score":51,"repay":true},{"score":52,"repay":true},{"score":52,"repay":true},{"score":52,"repay":true},{"score":53,"repay":true},{"score":53,"repay":true},{"score":53,"repay":true},{"score":54,"repay":true},{"score":54,"repay":true},{"score":54,"repay":true},{"score":54,"repay":true},{"score":55,"repay":true},{"score":55,"repay":true},{"score":55,"repay":true},{"score":56,"repay":true},{"score":56,"repay":true},{"score":56,"repay":true},{"score":56,"repay":true},{"score":57,"repay":true},{"score":57,"repay":true},{"score":57,"repay":true},{"score":57,"repay":true},{"score":58,"repay":true},{"score":58,"repay":true},{"score":58,"repay":true},{"score":58,"repay":true},{"score":59,"repay":true},{"score":59,"repay":true},{"score":59,"repay":true},{"score":59,"repay":true},{"score":60,"repay":true},{"score":60,"repay":true},{"score":60,"repay":true},{"score":61,"repay":true},{"score":61,"repay":true},{"score":61,"repay":true},{"score":61,"repay":true},{"score":62,"repay":true},{"score":62,"repay":true},{"score":62,"repay":true},{"score":62,"repay":true},{"score":63,"repay":true},{"score":63,"repay":true},{"score":63,"repay":true},{"score":63,"repay":true},{"score":64,"repay":true},{"score":64,"repay":true},{"score":64,"repay":true},{"score":64,"repay":true},{"score":65,"repay":true},{"score":65,"repay":true},{"score":65,"repay":true},{"score":66,"repay":true},{"score":66,"repay":true},{"score":66,"repay":true},{"score":66,"repay":true},{"score":67,"repay":true},{"score":67,"repay":true},{"score":67,"repay":true},{"score":68,"repay":true},{"score":68,"repay":true},{"score":68,"repay":true},{"score":69,"repay":true},{"score":69,"repay":true},{"score":70,"repay":true},{"score":70,"repay":true},{"score":70,"repay":true},{"score":71,"repay":true},{"score":71,"repay":true},{"score":72,"repay":true},{"score":72,"repay":true},{"score":73,"repay":true},{"score":73,"repay":true},{"score":74,"repay":true},{"score":75,"repay":true},{"score":76,"repay":true},{"score":76,"repay":true},{"score":77,"repay":true},{"score":79,"repay":true},{"score":81,"repay":true},{"score":83,"repay":true},{"score":17,"repay":false},{"score":19,"repay":false},{"score":21,"repay":false},{"score":23,"repay":false},{"score":24,"repay":false},{"score":24,"repay":false},{"score":25,"repay":false},{"score":26,"repay":false},{"score":27,"repay":false},{"score":27,"repay":false},{"score":28,"repay":false},{"score":28,"repay":false},{"score":29,"repay":false},{"score":29,"repay":false},{"score":30,"repay":false},{"score":30,"repay":false},{"score":30,"repay":false},{"score":31,"repay":false},{"score":31,"repay":false},{"score":32,"repay":false},{"score":32,"repay":false},{"score":32,"repay":false},{"score":33,"repay":false},{"score":33,"repay":false},{"score":33,"repay":false},{"score":34,"repay":false},{"score":34,"repay":false},{"score":34,"repay":false},{"score":34,"repay":false},{"score":35,"repay":false},{"score":35,"repay":false},{"score":35,"repay":false},{"score":36,"repay":false},{"score":36,"repay":false},{"score":36,"repay":false},{"score":36,"repay":false},{"score":37,"repay":false},{"score":37,"repay":false},{"score":37,"repay":false},{"score":37,"repay":false},{"score":38,"repay":false},{"score":38,"repay":false},{"score":38,"repay":false},{"score":38,"repay":false},{"score":39,"repay":false},{"score":39,"repay":false},{"score":39,"repay":false},{"score":39,"repay":false},{"score":40,"repay":false},{"score":40,"repay":false},{"score":40,"repay":false},{"score":41,"repay":false},{"score":41,"repay":false},{"score":41,"repay":false},{"score":41,"repay":false},{"score":42,"repay":false},{"score":42,"repay":false},{"score":42,"repay":false},{"score":42,"repay":false},{"score":43,"repay":false},{"score":43,"repay":false},{"score":43,"repay":false},{"score":43,"repay":false},{"score":44,"repay":false},{"score":44,"repay":false},{"score":44,"repay":false},{"score":44,"repay":false},{"score":45,"repay":false},{"score":45,"repay":false},{"score":45,"repay":false},{"score":46,"repay":false},{"score":46,"repay":false},{"score":46,"repay":false},{"score":46,"repay":false},{"score":47,"repay":false},{"score":47,"repay":false},{"score":47,"repay":false},{"score":48,"repay":false},{"score":48,"repay":false},{"score":48,"repay":false},{"score":49,"repay":false},{"score":49,"repay":false},{"score":50,"repay":false},{"score":50,"repay":false},{"score":50,"repay":false},{"score":51,"repay":false},{"score":51,"repay":false},{"score":52,"repay":false},{"score":52,"repay":false},{"score":53,"repay":false},{"score":53,"repay":false},{"score":54,"repay":false},{"score":55,"repay":false},{"score":56,"repay":false},{"score":56,"repay":false},{"score":58,"repay":false},{"score":59,"repay":false},{"score":61,"repay":false},{"score":63,"repay":false}]""")

# then we convert to a dataframe
people = pd.DataFrame(data)
people.to_csv("data/people_onegroup.csv", index=False)
```

```{python}
#| echo: true
people = pd.read_csv("data/people_onegroup.csv")
people.head()
```

```{python}
people.info()
```

```{python}
px.histogram(people, x="score", color="repay", nbins=100)
```

## Part 1: EDA


### Part 1a: Counts

How many people repayed? What fraction of them did?


Try doing this in two ways. First, use the usual grouping and counting pattern, but add a column for the fraction of people in each group. (Divide the `size` column by the total number of people in the dataset)

```{python}
repay_counts = people.groupby('repay', as_index=False).size()
repay_counts['fraction'] = repay_counts['size'] / repay_counts['size'].sum()
repay_counts
```

Alternative way: think about what this does:

```{python}
#| echo: true
people['repay'].sum()
```

What if we changed `.sum` to `.mean`? (I call this the "sum-as-count pattern".)

### Part 1b: Mean scores

What was the mean `score` for people who repayed? What was the mean `score` for people who didn't?

```{python}
people.groupby('repay', as_index=False)['score'].mean()
```

## Part 2: Thresholds

1. On the website, pick a threshold that results in all 4 colors being visible; it's especially visible in the Positive Rate pie.
2. Assign that threshold to a variable in your `qmd`.
3. Add a new column, `granted`, to the `people` dataframe that indicates if the bank grants the loan. Like the website, grant a loan if the score exceeds the `threshold`.
4. How many loans were granted?

Here's an example for a `threshold` of 64.

```{python}
threshold = 64
people['granted'] = people['score'] > threshold
people.head()
```


## Part 3: Metrics

We'll start by making a confusion matrix for the classifier. You'll find the following helpful:

```{python}
#| echo: true
crosstab = pd.crosstab(people['granted'], people['repay'])
(a, b), (c, d) = crosstab.values
```

In your document, replace `a`, `b`, `c`, and `d` with names like `false_positive` and `true_negative` (or `fp` and `tn`).

2. Compute and show the Positive Rate, the True Positive Rate, and Correctness. Check all of your results against the webapp; the numbers should be close although they may differ slightly because the data was not constructed identically.

```{python}
positive_rate = people['granted'].mean()
true_positive_rate = people.query('repay')['granted'].mean()
correctness = (people['granted'] == people['repay']).mean()
print(f"Positive Rate: {positive_rate:.3f}")
print(f"True Positive Rate: {true_positive_rate:.3f}")
print(f"Correctness: {correctness:.3f}")
```

3. Compute and show the precision and recall of this classifier.

## Part 4: Trade-offs

Adjust the `threshold` to maximize the Correct rate. What is the True Positive Rate then? 

What trade-off do we have to make if we want to maximize True Positive Rate instead?

Give specific examples of thresholds that achieve these objectives.
