---
title: "Trees"
icon: "file-slides"
format:
  revealjs:
    theme: [default, slides.scss]
    scrollable: true
    revealjs-plugins:
      - "fix-plotly-size"
execute: 
  echo: true
---

Imports ...

```{python}
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
import plotly.express as px
import plotly.io as pio
pio.templates.default = "plotly_white"
```

## Example: Blood test for autism?

We'll use an example from a [2017 PLOS Computational Biology paper](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005385). Download the [data](https://doi.org/10.1371/journal.pcbi.1005385.s001).

- Typically autism is diagnosed by behavioral symptoms
- If we could diagnose autism from a blood test, we could diagnose it earlier

The data has units on the second row, so we'll skip that row.

```{python}
autism = pd.read_csv("data/autism.csv", skiprows=[1])
```


---

```{python}
#| output: asis
#| echo: false
print(f"""
We have 3 kinds of data about {autism.shape[0]} children:
""")
```

1. The outcome (`Group`): ASD (diagnosed with ASD), SIB (sibling not diagnosed with ASD), and NEU (age-matched neurotypical children, for control)

```{python}
autism.groupby("Group", as_index=False).size()
```

---

## {.smaller}

1. The outcome (`Group`): ASD, SIB, NEU
2. Concentrations of various metabolites in a blood sample:

```{python}
#| echo: fenced
#| output: asis
print('\n'.join(f'- {column_name}' for column_name in autism.columns[1:-1]))
```

---

1. The outcome (`Group`): ASD, SIB, NEU
2. Concentrations of various metabolites in a blood sample
3. For the ASD children only, a measure of life skills ("Vineland ABC")

```{python}
autism.groupby("Group", as_index=False).agg(mean_vineland=("Vineland ABC", "mean"))
```

---

## Exploratory Data Analysis (EDA)

What do these metabolites look like?


```{python}
#| output-location: slide
autism_long = (
    autism
    .melt(id_vars="Group", var_name="Measure", value_name="value")
    .query("Group != 'SIB' and Measure != 'Vineland ABC'")
)
px.box(
    autism_long,
    x="value",
    y="Measure",
    facet_col="Group"
)
```

---

## EDA

- This plot helps us compare different metabolites *within* each group.
- Better question for predictive task: **Which of these metabolites help us *distinguish* autism?**

Approach: 

- easier to compare *within* a plot than *across* a facet, so switch y variable to Group.
- absolute values don't matter much, so let each metabolite have its own x scale.
- plotly boxplots don't show up well when small, so switch to a ridgeline plot

---

```{python}
#| output-location: slide
(
    px.violin(
        autism_long,
        x="value",
        y="Group",
        facet_col="Measure", facet_col_wrap=5
    )
    .update_traces(side="positive", width=3, points=False)
    .update_xaxes(matches=None)
    .for_each_annotation(lambda a: a.update(text=a.text.split("=", 1)[-1], font_size=10))
)
```

---

## Can we predict ASD vs non-ASD from metabolites?

- Let's start by (1) ignoring the behavior scores (that's an *outcome*) and comparing
just ASD and NEU.
- We need to drop SIB.

```{python}
feature_columns = list(autism.columns[1:-1])
target_column = "Group"

positive_outcome = "ASD"
negative_outcome = "NEU"
```


```{python}
data = (
    autism
    .query("Group != 'SIB'")
    [feature_columns + [target_column]]
)
print(data.shape)
```

## Train-test split

```{python}
from sklearn.model_selection import train_test_split
train, test = train_test_split(data, test_size=0.25, random_state=123)
print("Training set shape: {}".format(train.shape))
print("Test set shape: {}".format(test.shape))
```

## First Model: guessing most common

What if we always guessed the most common outcome?

```{python}
from sklearn.dummy import DummyClassifier
most_common = DummyClassifier(strategy="most_frequent").fit(
    X=train[feature_columns],
    y=train[target_column]
)
test["pred_most_common"] = most_common.predict(test[feature_columns])
accuracy_score(test[target_column], test["pred_most_common"])
```

## Confusion Matrix for most common

```{python}
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
ConfusionMatrixDisplay.from_estimator(
    estimator=most_common,
    X=test[feature_columns],
    y=test[target_column],
    labels=[positive_outcome, negative_outcome]
)
```

## Uniform Random Guess

Or what if we guess uniformly at random?

```{python}
uniform = DummyClassifier(strategy="uniform", random_state=0).fit(
    X=train[feature_columns],
    y=train[target_column]
)
test["pred_uniform"] = uniform.predict(test[feature_columns])
accuracy_score(test[target_column], test["pred_uniform"])
```

## Confusion Matrix for Guessing Uniformly {.smaller}

```{python}
#| echo: false
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
ConfusionMatrixDisplay.from_estimator(
    estimator=uniform,
    X=test[feature_columns],
    y=test[target_column],
    labels=[positive_outcome, negative_outcome]
)
```

Exercise: compute the following for this classifier:

- Accuracy
- False positive rate
- False negative rate
- Sensitivity
- Specificity
- Precision
- Recall

## Computing these automatically

Now we can compute them (see [docs on classification metrics](https://scikit-learn.org/stable/modules/model_evaluation.html#classification-metrics))

```{python}
from sklearn.metrics import classification_report
print(classification_report(
    y_true=test[target_column],
    y_pred=test["pred_uniform"],
))
```

Let's compute these quantities straight from the confusion matrix.

```{python}
from sklearn.metrics import confusion_matrix
(tn, fp), (fn, tp) = confusion_matrix(
    y_true=test[target_column],
    y_pred=test["pred_uniform"],
    labels=[negative_outcome, positive_outcome]
)
num_positives = tp + fn
num_negatives = tn + fp
print(f"Accuracy: {(tp + tn) / (num_positives + num_negatives):.2f}")
print(f"False positive rate: {fp / num_negatives:.2f}")
print(f"False negative rate: {fn / num_positives:.2f}")
print(f"Sensitivity / recall: {tp / num_positives:.2f}")
print(f"Specificity: {tn / (tn + fp):.2f}")
print(f"Precision: {tp / (tp + fp):.2f}")
```

## Decision Tree

```{python}
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(max_depth=1).fit(
    X=train[feature_columns],
    y=train[target_column]
)
train["pred_tree"] = tree.predict(train[feature_columns])
print("Training accuracy: ", accuracy_score(train[target_column], train["pred_tree"]))
```

. . .

```{python}
test["pred_tree"] = tree.predict(test[feature_columns])
print("Test accuracy: ", accuracy_score(test[target_column], test["pred_tree"]))
```

## Confusion Matrix

```{python}
ConfusionMatrixDisplay.from_estimator(
    estimator=tree,
    X=test[feature_columns],
    y=test[target_column],
    labels=[positive_outcome, negative_outcome]
)
```

## What does the tree look like?

```{python}
from sklearn.tree import plot_tree
plot_tree(tree, feature_names=feature_columns, class_names=[negative_outcome, positive_outcome]);
```

## Go Deeper

```{python}
#| code-line-numbers: "1"
tree = DecisionTreeClassifier(max_depth=2).fit(
    X=train[feature_columns],
    y=train[target_column]
)
train["pred_tree"] = tree.predict(train[feature_columns])
print("Training accuracy: ", accuracy_score(train[target_column], train["pred_tree"]))
```


```{python}
plot_tree(tree, feature_names=feature_columns, class_names=[negative_outcome, positive_outcome]);
```

. . .

```{python}
test["pred_tree"] = tree.predict(test[feature_columns])
print("Test accuracy: ", accuracy_score(test[target_column], test["pred_tree"]))
```


## Even Deeper

```{python}
#| code-line-numbers: "1"
tree = DecisionTreeClassifier(max_depth=30).fit(
    X=train[feature_columns],
    y=train[target_column]
)
train["pred_tree"] = tree.predict(train[feature_columns])
print("Training accuracy: ", accuracy_score(train[target_column], train["pred_tree"]))
```


```{python}
plot_tree(tree, feature_names=feature_columns, class_names=[negative_outcome, positive_outcome]);
```

What do you think the test accuracy will be?

. . .

```{python}
test["pred_tree"] = tree.predict(test[feature_columns])
print("Test accuracy: ", accuracy_score(test[target_column], test["pred_tree"]))
```

# Activity

## Training Data

```{python}
#| echo: false
# TODO: regression tree instead.
example_columns = ["% oxidized", "fCystine", "fGSH"]
example_target = target_column

example_data = (
    autism
    .query("Group != 'SIB'")
    [example_columns + [example_target]]
)

example_train, example_test = train_test_split(example_data, test_size=0.25, random_state=123)

student_data_subsets = [
    example_train.sample(n=5, random_state=x)
    for x in range(10)
]

for i, student_data in enumerate(student_data_subsets):
    display(f"Dataset {i}")
    display(student_data.style.hide(axis='index'))

test_subset = example_test.sample(n=5, random_state=0)
display("Test set")
display(test_subset[example_columns].style.hide(axis='index'))
```

## Instructions

1. Pick a random number between 0 and 9 (inclusive). This is your dataset number.
2. On paper, construct a decision tree to predict `Group` from the features in your dataset.
    - This doesn't have to be the *best possible* tree; just try to come up with *some* reasonable tree.
3. Write down what your tree predicts for each item in the test set.

Don't peek beyond this slide until you're done!

## Evaluation

Here's the test set with labels:

```{python}
#| echo: false
test_subset.style.hide(axis='index')
```

Compute your accuracy.

