project:
  type: "website"
  output-dir: _site
  render:
    - "*.qmd"
    - "!private"
    - "!*-soln.qmd"
    - "!*-template.qmd"
  post-render: "rsync -r static/ _site"

website:
  title: "DATA 202 (Wrangling and Analytics), Fall 2023"
  site-url: "https://calvin-data-science.github.io/data202/"
  navbar:
    right:
      - index.qmd
      - text: "RStudio"
        href: "https://r.cs.calvin.edu/"
  sidebar:
    contents:
      - "meetings.qmd"
      - section: "Projects"
        icon: "kanban"
        contents:
          - midterm-proj.qmd
          - final-proj.qmd
      - section: "Notes"
        icon: "pencil"
        contents: "notes/*"
      - section: "Units"
        icon: "book-half"
        contents:
          - auto: "units/01intro"
          - auto: "units/03vis1"
          - auto: "units/04vis2"
          - auto: "units/05wrangle1"
  page-navigation: true

format:
  html:
    css: styles.css
    toc: true
    toc_depth: 2
    toc_float: true

execute:
  freeze: auto
  daemon: 3600
