---
title: "Class Meetings"
subtitle: "DATA 202 Fall 2023"
format:
  html: default
  revealjs:
    output-file: "meetings-slides.html"
    scrollable: true
    title-slide-attributes:
        data-state: "hide-menubar"
    center: true
    menu: false
    section-divs: true
    simplemenu:
        barhtml:
            header: "<div class='menubar'><ul class='menu'></ul><div>"
        scale: 0.67
revealjs-plugins:
    - simplemenu
---

# Week 5 {data-stack-name="Week 5"}

## Monday

- [Slides: Wrangling Intro](units/05wrangle1/w05-wrangling.html)

## Wednesday

- [Wrangling exercises](units/05wrangle1/w05d2-wrangle-hotels.html)

## Friday

- Q&A
- Quiz 2
- Exercise 5
- Please check in with me about your project

# Week 6 {data-stack-name="Week 6"}

## Monday

- Q&A
- Reading 6 updated (actually includes ch7)
- Midterm project reminders
- [Slides: joining tables](/units/06wrangle2/w6-join.html)
- Last 20 minutes: working on Exercise 5

## Wednesday

- Q&A
- [Slides: tidying](/units/06wrangle2/w6-tidy.html)
- Start [Exercise 6](/units/06wrangle2/ex06-pivot-join.html)
- Work on project

## Friday

- Q&A
- When should quiz be?
- Exercise 6
- Work on project

# Week 7 {data-stack-name="Week 7"}

## 7.1 (Mon): class

- Exercise 6 Debugging
- Work on project

## 7.2 (Wed): class

- Some [slides](units/06wrangle2/w7-tidyvis.html) on tidying and visualizing
- Work on project

## Friday: Fall Break

# Week 8 {data-stack-name="Week 8"}

## Monday: Fall Break

## Wednesday: Advising

## 8.3 (Fri): lab

- Quiz 3
- Project showcase
    - Show your project to others in your row
    - Give and receive suggestions
    - Revise your project accordingly

# Week 9 {data-stack-name="Week 9"}

## 9.1 (Mon): Intro to ML

- [Slides](units/09supervised-intro/w09-supervised.html)
- Activity: [Teachable Machine](https://teachablemachine.withgoogle.com/)

Referenced in class:

- [The Shape of Actions](https://mitpress.mit.edu/9780262526524/the-shape-of-actions/)
- [‘Good Grief, Apple’—John Piper’s Watch Mistakes His Preaching for a Hard Fall, Prompts Call to Emergency Services](https://churchleaders.com/news/441896-john-piper-watch-mistakes-preaching-for-hard-fall.html)
- God's covenants of predictable universe:
    - [Genesis 8:22](https://www.biblegateway.com/passage/?search=Genesis+8%3A22&version=NIV)
    - [Jeremiah 33:25](https://www.biblegateway.com/passage/?search=Jeremiah+33%3A25&version=NIV)
    - ...

## 9.2 (Wed): ML

- Classification vs regression
- Workflow

Referenced in class:

- [Ken Arnold (Calvin U) - Sentiment Bias in Predictive Text Recommendations Results in Biased Writing](https://kenarnold.org/pubs/sentiment-bias/) and an independent and better replication: [Co-Writing with Opinionated Language Models Affects Users' Views | Abstract](https://arxiv.org/abs/2302.00560)
- [Puppies Or Food? 12 Pics That Will Make You Question Reality | Bored Panda](https://www.boredpanda.com/dog-food-comparison-bagel-muffin-lookalike-teenybiscuit-karen-zack/)
- ["Why Should I Trust You?": Explaining the Predictions of Any Classifier | Abstract](https://arxiv.org/abs/1602.04938)
  - See screenshots [here](https://hackernoon.com/dogs-wolves-data-science-and-why-machines-must-learn-like-humans-do-41c43bc7f982)
- [Big data: the end of the scientific method? | Philosophical Transactions of the Royal Society A: Mathematical, Physical and Engineering Sciences](https://royalsocietypublishing.org/doi/10.1098/rsta.2018.0145)

## 9.3 (Fri) lab

- [Exercise 9](units/09supervised-intro/ex09-supervised-intro.html)
    - Suggestion: skip the EDA section at first, come back to it after training a model.
- Visit the [Summer Research Poster Fair](https://calvin.edu/events/poster-fair/) this afternoon 12:30-3:30pm in Science Building

# Week 10 {data-stack-name="Week 10"}

## 10.1 (Mon): Metrics and Trees

- Slides: [Metrics](units/10trees/w10d1-metrics.html), [Trees](units/10trees/w10-trees.html).

References:

- [Spurious Correlations](https://www.tylervigen.com/spurious-correlations)

## 10.2 (Wed): Trees

- Slides: [Trees](units/10trees/w10-trees.html).
- Make-your-own-tree activity

## 10.3 (Fri): lab

- Quiz 4
- Finish make-your-own-tree activity
- [Exercise 10](units/10trees/ex10-metrics.html)

# Week 11 {data-stack-name="Week 11"}

## 11.1 (Mon): Random Forests and Linear Models

- [Slides](units/11model-zoo/w111model-types.html)

Referenced in class:

- APGAR score: [APGAR score | Wikipedia](https://en.wikipedia.org/wiki/APGAR_score)
- book: [Reset by David Murray](https://store.thegospelcoalition.org/tgc/products/1643/reset)
- [Psalm 127](https://www.biblegateway.com/passage/?search=psalm+127%3A2&version=NIV&interface=print)

## 11.2 (Wed): Bayesian Networks

- [Slides](units/11model-zoo/bayesnets.html)
- [Homo Deus](https://www.amazon.com/s?k=9781910701874) by [Yuval Noah Harari](https://en.wikipedia.org/wiki/Yuval_Noah_Harari) - "dataism"
- practicing the *present* presence of God, rather than representations that we can control but that are limited by interfaces
    - [The Paradox of Control - by L. M. Sacasas](https://theconvivialsociety.substack.com/p/the-paradox-of-control#details)
    - [The Uncontrollability of the World](https://www.wiley.com/en-us/The+Uncontrollability+of+the+World-p-9781509543168)

## 11.3 (Fri): Exercise on Bayesian Networks

- [Exercise 11](units/11model-zoo/ex11-bayesnets.html)

# Week 12 {data-stack-name="Week 12"}

## 12.1 (Mon): Linear Regression and Classification

- [Slides](units/12validation/w12logistic.html)

Things referenced:

- [Philemon](https://www.biblegateway.com/passage/?search=Philemon%201&version=NIV&interface=print) - reframing our relationships

## 12.2 (Wed): Classification and Cross-Validation

- [Slides](units/12validation/w12logistic.html)

## 12.3 (Fri): Exercise 12

- [Exercise](units/12validation/ex12clf-validation.html)
- No quiz today (sorry, didn't get to prep it)
- Opportunity to discuss projects in class

# Week 13 {data-stack-name="Week 13"}

## 13.1 (Mon): LLMs

- Topics Poll
- Large Language Models: [Slides](units/13llm/w13llm.html), [activity](units/13llm/explore-lm.html)

# Week 14 {data-stack-name="Week 14"}

## 14.1 (Mon): Unsupervised Learning

- [Slides](units/14unsupervised/w14unsupervised.html)
- [Exercise](units/14unsupervised/ex14clustering.html)

## 14.2 (Wed): Research Talks

- 8am section: [Abraham Woubie](https://scholar.google.com/citations?user=YyhFChIAAAAJ&hl=en)
- 9:15am section: [Ken Arnold](https://kenarnold.org/)

## 14.3 (Fri): Databases and SQL

- Quiz
- SQL Exercise: [SQL Murder Mystery](https://mystery.knightlab.com/)

## 15.1 (Mon): Explaining Predictions

- [Slides](units/14unsupervised/w14interpretable.qmd)

## 15.2 (Wed): Missing Data, Ethics and Social Impacts, Wrap-Up

- [Slides](units/14unsupervised/wrapup.html)
- Referenced in class:
    - An example of good storytelling [Harry Collins - Wikipedia](https://en.wikipedia.org/wiki/Harry_Collins)
