---
title: "Homework 3: Bike Sharing Data Wrangling"
author: "YOUR NAME"
date: "TODAY'S DATE"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)

# Disable a warning message.
options(dplyr.summarise.inform = FALSE)
```


## Load Data

```{r load-data}
# Read the file, specifying data types for each column.
rides_2011 <- read_csv("data/rides_2011.csv.gz", col_types = cols(
  start_time = col_datetime(),
  duration = col_double(),
  member_type = col_factor()
))
rides_2012 <- read_csv("data/rides_2012.csv.gz", col_types = cols(
  start_time = col_datetime(),
  duration = col_double(),
  member_type = col_factor()
))
```

## Exercise 1

```{r bind-rows}

```

*Your narrative answer here.*

## Exercise 2

*Your narrative answer here.*

```{r}
# Your code here. Be sure to give this code chunk a meaningful label.
```

## Exercise 3

```{r}
# Your code here. Be sure to give this code chunk a meaningful label.
```

## Exercise 4

```{r}
# Your code here. Be sure to give this code chunk a meaningful label.
```

*Your narrative answer here.*

## Exercise 5

```{r}
# Your code here. Be sure to give this code chunk a meaningful label.
```

## Exercise 6

Add code blocks as needed for this and remaining exercises.

## Exercise 7


## Exercise 8


## Exercise 9
