---
title: "Homework 3: Bike Sharing Data Wrangling"
author: "YOUR NAME"
date: "TODAY'S DATE"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)

# Disable a warning message.
options(dplyr.summarise.inform = FALSE)
```


## Load Data

```{r load-data}
# Read the file, specifying data types for each column.
rides_2011 <- read_csv("data/rides_2011.csv.gz", col_types = cols(
  start_time = col_datetime(),
  duration = col_double(),
  member_type = col_factor()
))
rides_2012 <- read_csv("data/rides_2012.csv.gz", col_types = cols(
  start_time = col_datetime(),
  duration = col_double(),
  member_type = col_factor()
))
```

## Exercise 1

```{r bind-rows}
rides <- bind_rows(
  rides_2011,
  rides_2012
)
```

There are `r nrow(rides)` rides in this dataset.

## Exercise 2

`duration` is probably measured in seconds, because most rides are less than 30 * 60 seconds (30 minutes), but 
some are as long as `r format(max(rides$duration), scientific = FALSE, big.mark = ",")`, which is most of a day (86,400 seconds).

```{r duration-hist}
rides %>% 
  ggplot(aes(x = duration)) +
    geom_histogram(binwidth = 30 * 60)
```

## Exercise 3

```{r count-member-type}
rides %>%
  count(member_type)
```

## Exercise 4

```{r aggregate-hourly}
hourly_rides <- rides %>%
  group_by(start_hour = floor_date(start_time, unit = "hours")) %>% 
  count()
```

## Exercise 5

```{r count-by-hour-and-member-type}
hourly_rides <- rides %>%
  group_by(hour = floor_date(start_time, unit = "hours"), member_type) %>% 
  summarize(rides = n())
```

## Exercise 6

```{r count-by-day-and-member-type}
daily_rides <- rides %>%
  group_by(day = floor_date(start_time, unit = "days"), member_type) %>% 
  summarize(rides = n())
```

## Exercise 7

```{r rides-by-weekday}
hourly_rides %>%
  filter(member_type != "Unknown") %>% 
  ggplot(aes(x = wday(hour, label = TRUE), y = rides, fill = member_type)) +
  geom_boxplot() +
  labs(y = "Rides", x = "Day of Week", fill = "Type of Rider")
```

## Exercise 8

```{r rides-by-weekday-table, echo=FALSE}
hourly_rides %>% 
  filter(member_type != "Unknown") %>% 
  group_by(weekday = wday(hour, label = TRUE), member_type) %>% 
  summarize(median_rides = median(rides)) %>% 
  pivot_wider(names_from = member_type, values_from = median_rides) %>% 
  knitr::kable()
```


## Exercise 9

```{r ride-distributions-by-hour, fig.height=10, fig.width=10}
hourly_rides %>% 
  filter(member_type != "Unknown") %>% 
  mutate(is_weekend = if_else(
    wday(hour, label = TRUE) %in% c("Sat", "Sun"),
    "Weekend", "Weekday")) %>% 
  ggplot(aes(x = as_factor(lubridate::hour(hour)), y = rides, fill = member_type)) + 
    geom_boxplot() +
    facet_wrap(~ is_weekend, scales = "free_y", nrow = 2)
```
