---
title: "14: Unsupervised Learning, etc."
---

# Objectives


# Reading

## Unsupervised Learning

- Skim the [Wikipedia article on cluster analysis](https://en.wikipedia.org/wiki/Cluster_analysis)
    - What is a "clustering"?
    - What is the difference between "hard clustering" and "soft clustering"?
    - Evaluation: What is the difference between "internal" and "external" evaluation?
    - Applications: what are some applications of clustering in two diferent fields of interest to you?
- k-means clustering
    - [Wikipedia article](https://en.wikipedia.org/wiki/K-means_clustering)
    - [Scikit-learn documentation](http://scikit-learn.org/stable/modules/clustering.html#k-means)
    - [Scikit-learn example](http://scikit-learn.org/stable/auto_examples/cluster/plot_cluster_iris.html)
    - Can you explain what's wrong in each subplot of the "[Unexpected KMeans clusters](https://scikit-learn.org/stable/auto_examples/cluster/plot_kmeans_assumptions.html)" figure?

## Interpretation and Explainability

- [Interpretable Machine Learning](https://christophm.github.io/interpretable-ml-book/)

Specific methods:

- [sklearn User Guide: Permutation feature importance](https://scikit-learn.org/stable/modules/permutation_importance.html)
- [sklearn User Guide: Partial dependence plots](https://scikit-learn.org/stable/modules/partial_dependence.html)
- Shapley and SHAP
    - [Interpretable Machine Learning book chapter](https://christophm.github.io/interpretable-ml-book/shapley.html) (source for the bikeshare example)
    - Kaggle course (source for the soccer example): [SHAP Values](https://www.kaggle.com/dansbecker/shap-values)
    - [SHAP: A Unified Approach to Interpreting Model Predictions](https://arxiv.org/abs/1705.07874)
- Decision Rules: [Interpretable Machine Learning book chapter](https://christophm.github.io/interpretable-ml-book/rules.html)

Going further:

- [Interpretable Machine Learning](https://christophm.github.io/interpretable-ml-book/)
- [Interpretable Machine Learning: Fundamental Principles and 10 Grand Challenges](https://arxiv.org/pdf/2103.11251.pdf)
- [Stop explaining black box machine learning models for high stakes decisions and use interpretable models instead | Nature Machine Intelligence](https://www.nature.com/articles/s42256-019-0048-x)
[Dissecting scientific explanation in AI (sXAI): A case for medicine and healthcare - ScienceDirect](https://www.sciencedirect.com/science/article/abs/pii/S0004370221000497)

## Ethics and Fairness

- Book: [Fairness and machine learning](https://fairmlbook.org/)
    - chapter we referenced in class: [When is automated decision making legitimate?](https://fairmlbook.org/legitimacy.html)
