---
title: "What makes a good prediction?"
author: "K Arnold"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    self_contained: FALSE
    lib_dir: libs
    nature:
      ratio: "16:9"
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE, message=FALSE}
source("../slides-common.R")
slideSetup()
knitr::opts_chunk$set(echo = TRUE)
```

## Objectives

* Compare and contrast regression tasks and classification tasks, and give examples of each
* Identify two different ways of measuring accuracy for regression and for classification
* Identify several reasons why a model may predict better on some subsets of data than others

---

## Types of Tasks

* **regression**
* **classification**

---

## What makes a good prediction? *Regression*

* **residual**: actual minus predicted
  * If home sold for \$200k but we predicted \$250k, residual is ____
* (statistical) *bias*: overpredicts vs underpredicts
* absolute error
* squared error
* normalized squared error: MSE / Variance
  * The confusingly named "R-two": 1 - normalized squared error

---

## What makes a good prediction? *Classification*


|                        | Email is spam                 | Email is not spam             |
|------------------------|-------------------------------|-------------------------------|
| Email labeled spam     | True positive                 | False positive (Type 1 error) |
| Email labeled not spam | False negative (Type 2 error) | True negative                 |

--
- **Accuracy** (% correct) = (TP + TN) / (# emails)
- **False negative** ("miss") **rate** = FN / (# true spam)
- **False positive** ("false alarm") **rate** = FP / (# true not-spam)

--
- **Sensitivity** ("true positive rate") = TP / (# true spam)
  - Sensitivity = 1 − False negative rate
- **Specificity** ("true negative rate") = TN / (# true spam)
  - Specificity = 1 − False positive rate
- [Wikipedia article](https://en.wikipedia.org/wiki/Sensitivity_and_specificity)

---

.question[
If you were designing a spam filter, would you want sensitivity and specificity to be high or low? What are the trade-offs associated with each decision? 
]

---

## Validation

*Example: perfectly predicting home price from irrelevant predictors*

