---
title: "Practice with Data Transformation"
author: "K Arnold"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    self_contained: FALSE
    lib_dir: libs
    nature:
      ratio: "16:9"
      highlightLines: true
      highlightStyle: solarized-dark
      countIncrementalSlides: false
---

```{r include=FALSE, message=FALSE}
source("../slides-common.R")
slideSetup()
```

layout: true

## Proposed Structure Changes

Feedback welcome!

---

---

* Lab
  * still due on Monday
  * But instead of working on it only on Fridays...
  * we'll be working a little each class meeting.
  
---

* Lab
* Quizzes
  * Prep quiz: unlimited attempts, categorized as Prep
  * Post-class quizzes will sometimes include add an easy but graded question from the day's Lab,
    closes beginning of next class meeting (unless you ask me)
  * "Real" quiz: one attempt, closes Friday

---

* Lab
* Quizzes
* New semester-long discussion forums
  * *enrichment activities*: Do one or two optional activities throughout the semester, report back to the class
      * [ICPSR Data Fair](https://www.icpsr.umich.edu/web/pages/membership/datafair/index.html) next week, ["Philosophy of Data Science" podcast](https://www.podofasclepius.com/philosophy-of-data-science), propose others!
  * *Data Science in the News*: share current events related to DS
      * Articles that *use* data science to tell a story
      * Articles *about* data science

---
layout: false

## Resources

* [Cheatsheets](https://rstudio.com/resources/cheatsheets/)
  * [Data Transformation](https://github.com/rstudio/cheatsheets/raw/master/data-transformation.pdf) (dplyr)
  * [Data Visualization](https://github.com/rstudio/cheatsheets/raw/master/data-visualization-2.1.pdf)
  * [R Markdown](https://github.com/rstudio/cheatsheets/raw/master/rmarkdown-2.0.pdf)

---

## Weekly Labs

* This week: [Nobel Laureates](../lab/lab03-nobel/)
* Next week: Covid-19 cases

Propose datasets or analyses you're interested in!
