---
title: "Exercise 6: Pivoting and Joining"
execute: 
  echo: false
---

This exercise has an in-class portion (ungraded) and an in-lab/homework portion.

The in-lab portion has not yet been put in this document.

## In-Class Exercises: gapminder


```{python}
import pandas as pd
import plotly.express as px
```

Download the data from <https://www.gapminder.org/data/> in either CSV or Excel format. Upload to RStudio and use either `pd.read_csv` or `pd.read_excel` to load it.

Step by step instructions, so we all get the same data:

- Go to <https://www.gapminder.org/data/>
- Under "Choose individual indicators", search for "GDP". Click the one marked "Income", it should say "GDP per capita (price and inflation adjusted, in PPP$2017)" when you click on it.
- At the top of the table, click Download As: CSV or XLSX. I got a file named `lex.xlsx`
- Click the header ("GDP per capita") and select instead "Life Expectancy, at birth". Download that as well. I got a file named `gdp_pcap.xlsx`

```{python}
#| echo: true
gapminder_gdp = pd.read_excel("data/gdp_pcap.xlsx")
gapminder_gdp.head()
```

```{python}
#| echo: true
gapminder_life = pd.read_excel("data/lex.xlsx")
gapminder_life.head()
```

## Wide to Long

Notice that the data is in "wide" format, with each year as a column. To join and plot this data, we'll need it in "long" format, with each year as a row:

```{python}
gdp_long = pd.melt(
    gapminder_gdp, id_vars=["country"], var_name="year", value_name="gdp_pcap")
gdp_long.head()
```

We'll use `pd.melt` to get it in this format. We'll need to tell it which columns form the primary key, specified by the `id_vars` argument. The other columns will be "melted" into a single column, specified by the `var_name` argument. The values for those columns will be put in a column specified by the `value_name` argument.

```{python}
#| eval: false
#| echo: true
pd.melt(
    gapminder_gdp,
    id_vars=[...],
    var_name="XXX", value_name="YYY"
)
```

Fill in the blanks above with the appropriate column names. Then assign the result to a variable; I used `gdp_long`.

Now repeat that for the life expectancy data:

```{python}
life_long = pd.melt(
    gapminder_life, id_vars=["country"], var_name="year", value_name="life")
life_long.head()
```

## Joining

Now, join the datasets together. Think about what the primary key of this data is. Call the result `gapminder`:

```{python}
gapminder = pd.merge(gdp_long, life_long, on=["country", "year"])
gapminder.head()
```

Validate your join by checking the number of rows in the result.

```{python}
n_unique_countries = len(gapminder_gdp['country'].unique())
n_years = gapminder_gdp.shape[1] - 1
print(f"{n_unique_countries} countries, {n_years} years")
print(f"{n_unique_countries * n_years=} expected rows")
print(f"{len(gapminder)} rows in result")
```

## Adding regions

The region data is available [here](https://www.gapminder.org/fw/four-regions/). `read_excel` can pull the data in directly for you. I'll save you some time by giving you that code:

```{python}
#| echo: true
region_data = pd.read_excel("https://docs.google.com/spreadsheets/d/1qHalit8sXC0R8oVXibc2wa2gY7bkwGzOybEMTWp-08o/export?format=xlsx", sheet_name="list-of-countries-etc")
region_data.head()
```

It has a lot of columns; we only want `four_regions`. Rename it to `region`. Then select the columns we want. Then join it with the `gapminder` data.

To rename, use `pd.rename(columns={"old_name": "new_name"})`. To select columns, use `df[["col1", "col2"]]`. Remember that both of these return a new dataframe, so you can chain the operations together, then assign the final result to a variable (I used `gapminder_with_regions`).

```{python}
gapminder_with_regions = (
    region_data.rename(columns={"four_regions": "region", "name": "country"})
    [["country", "region"]]
    .merge(gapminder, on="country")
)
```

## Plotting

Now you can make the plot. By now you should be able to do this without further guidance.

```{python}
px.scatter(
    gapminder_with_regions, x="gdp_pcap", y="life", animation_frame="year", color="region",
    log_x=True, range_y=[25, 95],
    hover_name="country"
)
```
