---
title: "Homework 2: Bike Sharing Data Visualization"
author: "YOUR NAME"
date: "TODAY'S DATE"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)

# Disable a warning message.
options(dplyr.summarise.inform = FALSE)
```

*Your introduction here*

## Read Data

```{r read-data, message=FALSE}
hourly_rides <- read_csv("data/hour.csv") %>%
  mutate(across(c(season, year, hour, holiday, workingday, day_of_week, weather_type, member_type), as.factor))
hourly_rides %>% glimpse()
```

## Exercise 1: Label days of week

```{r label-weekdays}
hourly_rides <- hourly_rides %>%
  mutate(day_of_week = factor(day_of_week, levels = c(0, 1, 2, 3, 4, 5, 6), labels = c("DAY", "ANOTHER DAY", "...", "...", "...", "...", "...")))
```

## Exercise 2: Overall counts by weekday

```{r ride-totals}
ride_totals <- hourly_rides %>%
  group_by(member_type, day_of_week) %>% 
  summarize(rides = sum(rides))
```

```{r ride-totals-by-weekday}
# your code here
```

## Exercise 3: Distribution of Rides by Weekday

```{r ride-distributions-by-weekday}
# your code here
```

## Exercise 4: Distribution of Rides by Hour

```{r ride-distributions-by-hour, fig.height=8}
# your code here
```

## Exercise 5: Overplotting

```{r rides-by-temp-overplot}
ggplot(hourly_rides, aes(x = temp, y = rides)) +
  geom_point() +
  facet_wrap(~ member_type) + 
  labs(x = "Normalized temperature", y = "Rides")
```

### Approach 1

```{r overplot-fix-1}

```

### Approach 2

```{r overplot-fix-2}

```

### Comparison

*Which do you prefer, and why?*
