---
title: "Exercise 3: Visualization Design"
execute: 
  echo: false
---

```{python}
import pandas as pd
import plotly.express as px

# DATA 202 hack for displaying plotly within RStudio:
if 'r' in globals() and r['.Platform$GUI'] == "RStudio" and r['suppressMessages(requireNamespace("htmltools"))']:
  r[".GlobalEnv$to_html <- function(x) { print(htmltools::HTML(x)) }"] and None
  def show_plot(p): r.to_html(p._repr_html_())
else:
  def show_plot(p): return p
# End hack
```

::: {.callout-important}
Please shutdown your RStudio session when you're not using it.
:::

In the past several exercises, you've typically been given a lot of template code and very specific instructions. This time, we'll do some of the same tasks, but without the training wheels.

Make your own `qmd` file, following the [Class Standards](../../notes/quarto.qmd#class-standards) (especially regarding the YAML header). You may use past exercises as inspiration, but avoid copy and paste except for the text in Class Standards.

```{python}
daily_rides = pd.read_csv("../../static/data/bikeshare/day_by_type.csv", parse_dates=["date"])
daily_rides['month'] = daily_rides['date'].dt.month
```


## Part 1

Replicate this plot, made using the ridership data from the previous exercise. Write one or two sentences about what it tells you.

```{python}
show_plot(
  px.scatter(
    daily_rides,
    x="date", y="rides", color="rider_type",
    facet_col="workingday",
    trendline="lowess",
    labels={"date": "Date", "rides": "Number of Rides", "rider_type": "Type of Rider"}
    )
    .update_traces(marker_size=3, marker_opacity=.5)
)
```

- [ ] Have you replicated the plot?
- [ ] Are all the labels correct?
- [ ] Have you set the marker size (attribute `marker_size`) to 3?
- [ ] Have you set the marker opacity (attribute `marker_opacity`) to 0.5?
- [ ] Have you written one or two sentences about what the plot tells you?

## Part 2

Make another plot of the same variables as in Part 1, but choose a different mapping of variables to visual cues. Write a sentence about what is now easier, or harder, to see in this plot compared with the previous one.

- [ ] Have you made a plot with the same variables as Part 1?
- [ ] Have you chosen a different mapping of variables to visual cues?
- [ ] Have you stated something that's easier to see in this plot compared with the previous one?

## Part 3

Now use the gapminder data; you may use the data from Plotly Express. The following code chunk also creates some filtered data frames that are needed for the following problems.

```{python}
#| echo: true
gapminder = px.data.gapminder()
just_usa = gapminder.query("country == 'United States'")

countries = [
  "China", "India", "United States",
  "Indonesia", "Brazil", "Pakistan",
  "Bangladesh", "Nigeria", "Japan"]

gapminder_9_countries = gapminder.query("country in @countries")
```

Make the following plot:

```{python}
show_plot(
  px.line(
    just_usa,
    x="year", y="lifeExp",
    labels={"year": "Year", "lifeExp": "Life Expectancy (years)"},
    title="Life Expectancy in the United States",
  )
  .update_traces(line_color='green')
)
```

- [ ] Are your axes labeled?
- [ ] Does the plot have a title?
- [ ] Is the line `green`? (The trace attribute is called `line_color`.)

## Part 4

Make two plots of the `gapmind_9_countries` data. Both plots should use `year`, `lifeExp`, and `country`, but one should use color for `country` and the other should use faceting (I suggest making the facets wrap). Compare and contrast the two plots: What is easier to see in one plot compared with the other?

- [ ] Are your axes labeled?
- [ ] Do the plots have titles?
- [ ] Do you have a plot colored by `country`?
- [ ] Do you have a plot that's faceted by `country`?
- [ ] Have you stated something that's easier to see in one plot compared with the other?

## Part 5

Replicate the [Gapminder "health and wealth"](https://www.gapminder.org/tools/#$chart-type=bubbles&url=v1) plot -- as much as you can.

- [ ] Markers are sized by `pop`? (you may want to use `size_max` to make the largest marker smaller)
- [ ] Markers are colored by `continent`?
- [ ] Animation is by `year` (`animation_frame`)?
- [ ] GDP axis is log-scaled (`log_x`)?
- [ ] Life expectancy doesn't go off the top of the plot (`range_y`)?
- [ ] Axes have correct labels?

Here's what one might look like:

```{python}
px.scatter(gapminder,
  x="gdpPercap", y="lifeExp", size="pop", color="continent", animation_frame="year", 
  log_x=True, size_max=60, range_x=[100,100000], range_y=[25,90],
  hover_name="country",
  labels={"gdpPercap": "GDP per capita", "lifeExp": "Life expectancy (at birth)", "pop": "Population", "continent": "Continent", "year": "Year"},
  title="Life expectancy vs. GDP per capita, 1952-2007",
)
```


## Reflection

At the end of your document, write a sentence or two of your overall reflections on this exercise. You may write whatever you want, but you might perhaps respond to one or two of these questions:

- Was anything unclear about this assignment?
- How hard was it for you? Where did you get "stuck"?
- How long did it take you?
- What questions or uncertainties remain?
- What skills do you think you'll need more practice with?
- Did you try anything out of curiosity that you weren't specifically asked to do?

::: {.callout-note}
We'll respond to these reflections in class, but only in an overall sense and only once we've had a chance to review them. If you have a question that needs a response, please post it on Perusall.
:::

## Submitting

Submit your rendered HTML file to Moodle. (Make sure it renders cleanly, and shows correctly on your computer.)

