---
title: "pandas"
execute: 
  output: false
---

# Quick Reference for Grammar of Data

```{python}
#| echo: false
import pandas as pd
colleges = pd.read_csv("../static/data/college_scorecard.csv")
```


## select columns

```{python}
colleges[['name', 'undergrads']]
```

Documentation on [indexing](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html)

Getting a single column as a `Series`:

```{python}
colleges['name']
```

Remember: column names are strings (not `colleges[name]`)!

## select rows (`query`)

```{python}
colleges.query("state == 'AK'")
```

Documentation: [pandas.DataFrame.query](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.query.html)

## top and bottom

```{python}
colleges.head(n=2)
```

```{python}
colleges.tail(n=3)
```

## arrange rows (`sort_values`)

```{python}
colleges.sort_values("undergrads").head()
```

```{python}
colleges.sort_values("undergrads", ascending=False).head()
```

Documentation: [pandas.DataFrame.sort_values](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_values.html)

## counting

```{python}
colleges.groupby("state", as_index=False).size()
```

## grouping / summarizing (general)

```{python}
students_by_state = (
  colleges
  .groupby("state", as_index=False) # <1> 
  .agg(total_undergrads=('undergrads', 'sum')) # <2>
  .sort_values("total_undergrads", ascending=False) # <3>
)
students_by_state
```
1. Group by state
2. `agg`regate: compute a `total_undergrads` column by (a) extracting the `undergrads` column, and (b) `sum`ming it
3. Sort the result by `total_undergrads`

Documentation on [grouping](https://pandas.pydata.org/docs/user_guide/groupby.html).

## grouping by multiple columns

```{python}
(
  colleges
  .groupby(["state", "online_only"], as_index=False)
  .agg(total_undergrads=('undergrads', 'sum'))
)
```

## random sampling

Shuffle rows:

```{python}
colleges.sample(frac=1.0).head()
```

Select random rows:

```{python}
colleges.sample(n=5)
```

## Deriving new columns

```{python}
colleges['named_university'] = colleges['name'].str.contains('University')
colleges.groupby('named_university', as_index=False).agg(
  mean_undergrads=('undergrads', 'mean'),
  max_undergrads=('undergrads', 'max')
)
```

Note: you can also *chain* these operations using `assign`, which *returns a new `DataFrame`* instead of modifying the original.

```{python}
(
  colleges
  .assign(named_university = colleges['name'].str.contains('University'))
  .groupby('named_university', as_index=False).agg(
    mean_undergrads=('undergrads', 'mean'),
    max_undergrads=('undergrads', 'max')
  )
)
```

## `SettingWithCopyWarning`

Deriving columns on a subset of rows can cause a warning. For example:

```{python}
#| output: true
mi_colleges = colleges.query("state == 'MI'")
mi_colleges['named_college'] = mi_colleges['name'].str.contains('College')
```

This is pandas trying to keep you from making certain types of mistakes that can be subtle; see the [documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy). To avoid it, use `assign`:

```{python}
mi_colleges = colleges.query("state == 'MI'")
mi_colleges = mi_colleges.assign(
  named_college = mi_colleges['name'].str.contains('College'))
```

or `.copy`:

```{python}
mi_colleges = colleges.query("state == 'MI'").copy()
mi_colleges['named_college'] = mi_colleges['name'].str.contains('College')
```


## "Broadcast" operations

Apply an operation to an entire column at a time.

```{python}
colleges['undergrads'] / 1000
```

```{python}
pd.isna(colleges['undergrads'])
```

## Pairs of columns

When broadcasting with a pair of columns, the operation is applied element-wise.

```{python}
colleges['city'] + ', ' + colleges['state']
```

::: {.callout-note}
For more advanced string concatenation, you may want to use `str.cat`:
`
```{python}
colleges['city'].str.cat(colleges['state'], sep=', ')
```
:::

## Deriving new columns, advanced

If you need an operation that isn't built into pandas, you can `apply` your own function. First let's define a function:

```{python}
#| output: true
def classify_name(school_name):
    school_name = school_name.lower()
    if 'university' in school_name:
        return 'university'
    elif 'college' in school_name:
        return 'college'
    else:
        return 'other'

# example:
classify_name('University of California, Berkeley')
```

Then we `apply` that to each row:

```{python}
colleges['name_type'] = colleges['name'].apply(classify_name)
```

```{python}
colleges.groupby('name_type', as_index=False).agg(
  mean_undergrads=('undergrads', 'mean'),
  max_undergrads=('undergrads', 'max')
)
```

Note: this is slower because it runs unoptimized Python code for each row. First, make it correct, then make it fast (e.g., [`np.select`](https://numpy.org/doc/stable/reference/generated/numpy.select.html)).

## Joining (`merge`)

If you think you want to:

```
for each row in table A:
  look up value in table B
```

then you want a join.

Example: looking up state names.

```{python}
#| output: true
states = pd.read_csv("../static/data/states.csv")
states.head()
```

```{python}
#| output: true
students_by_state_with_names = (
  students_by_state
  .merge(
    states,
    left_on='state', right_on='postal_code',
    how='left', indicator=True
  )
)

students_by_state_with_names.head()
```

```{python}
#| output: true
students_by_state_with_names.tail()
```

### Join types

- **Left join**: use keys from left table
- **Right join**: use keys from right table
- **Outer join**: use union of both sets of keys
- **Inner join**: use *intersection* of both sets of keys

See [documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html)

## Debugging joins

Always check your joins!

- Check the number of rows in the result
- Use `indicator=True` to see which rows came from which table
- Use [`validate`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html) to check that the join is correct. Options:
  - 'one_to_one' or '1:1': check if merge keys are unique in both left and right datasets.
  - 'one_to_many' or '1:m': check if merge keys are unique in left dataset.
  - 'many_to_one' or 'm:1': check if merge keys are unique in right dataset.
  - 'many_to_many' or 'm:m': allowed, but does not result in checks.

**Debugging tool**: Do an `outer` join, then `groupby` your primary key and the `_merge` indicator:

```{python}
#| output: true
students_by_state_with_names = (
  students_by_state
  .merge(
    states,
    left_on='state', right_on='postal_code',
    how='outer', indicator=True
  )
)

(
  students_by_state_with_names
  .groupby(['state', '_merge'], as_index=False)
  .size()
  .query("_merge != 'both' and size > 0")
)
```

Things that might be wrong:

- You mis-specified the primary key (e.g., it actually should be two columns)
- The keys don't match (e.g., one has "US" and the other has "United States")

Tools to fix key mismatches:

- `replace` to fix a small number of key mismatches
- when you have a large number of mismatches, `merge` with a *translation table*, then `fillna` from the translation table.
- To make a translation table, you might use fuzzy matching, using tools like [thefuzz](https://github.com/seatgeek/thefuzz) (but be careful)

## Web Scraping

You can use [`pd.read_html`](https://pandas.pydata.org/docs/user_guide/io.html#io-read-html) to read tables from web pages. This is actually how I made the `states.csv` file that we just read.

```{python}
states_tables_raw = pd.read_html("https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States", match="postal abbr")
print("Found", len(states_tables_raw), "tables")
states_tables_raw[-1]
```

Expect the result to be messy. Cleaning it up often requires doing things that are beyond the scope of this class, but here's one example:

```{python}
#| output: true
def clean_states_table(df):
  return (
    df
    .iloc[:, :2] # we only care about the first two columns
    .set_axis(['name', 'postal_code'], axis=1) # assign column names
    .dropna() # drop rows with missing values
    .assign(name = lambda df: df['name'].str.replace(r'\[.*\]', ''))
  )
cleaned_territories = clean_states_table(states_tables_raw[-1])
cleaned_territories
```

This is a good case for using `concat`:

```{python}
#| output: true
state_names = pd.concat([
  clean_states_table(table) for table in states_tables_raw
], ignore_index=True)
state_names
```

```{python}
#| echo: false
state_names.to_csv("../static/data/states.csv", index=False)
```

# Style notes

We'll use a consistent `pandas` style in this class.

- access columns with `df['col']`, not `df.col`
- no index
- `groupby` with `as_index=False`
- explicit aggregation
- `.size` of groups, not `value_counts`

Know the rules in order to know when to break them.

## No index

- pandas has `index`ing, an unusual concept
  - not used in SQL, tidyverse, spreadsheets, etc.
  - even [Ibis](https://ibis-project.org/), next-gen dataframe library by Wes McKinney (pandas creator), doesn't use it.
- it's sometimes useful, but often confusing, so we'll avoid it.
- so we'll use `as_index=False` in all our `groupby` calls.
  - so all our aggregation results will be `DataFrames`, not `Series`.

## Explicit aggregation

Lazy method:

```python
colleges.groupby("state", as_index=False).undergrads.mean()
```

Explicit method:

```python
colleges.groupby("state", as_index=False).agg(
  mean_undergrads=('undergrads', 'mean'),
  max_undergrads=('undergrads', 'max')
)
```

## Size of a group

Preferred to `value_counts`:

- works with multiple columns
- returns a `DataFrame`, not a `Series`

::: {.columns}
:::: {.column width="50%"}

```python
(
  colleges
  .groupby("state", as_index=False)
  .size()
)
```

:::
::: {.column width="50%"}

```python
(
  colleges
  .groupby(["state", "online_only"], as_index=False)
  .size()
)
```

:::
:::

Compare with `value_counts`:

```python
colleges["state"].value_counts()
```
