---
title: "Wrangling"
---

This document does all the data wrangling and pulling data in from R for DATA 202.

```{r setup}
library(tidyverse)

get_out_dir <- function(kind = '') {
  path <- "static/data/"
  if (kind != '') path <- paste0(path, kind, '/')
  out_dir <- here::here(path)
  if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)
  out_dir
}

get_out_filename <- function(filename, kind = '') {
  paste0(get_out_dir(kind = kind), filename)
}

```

```{r}
library(pins)
board <- board_connect()
```


## bikeshare


```{r wrangle-bikeshare}
# Exercise 1: simplified to total number of rides
daily_rides_all <- read_csv(here::here("data/bikeshare/day.csv"))
daily_rides <- daily_rides_all %>%
  mutate(workingday = as.factor(case_when(
    workingday == 1 ~ "workday",
    TRUE            ~ "weekend"))) %>% 
  select(
    date = dteday,
    day_of_week = weekday,
    workingday,
    total_rides = registered
  )

daily_rides_bytype <- daily_rides_all %>%
  mutate(workingday = case_when(workingday == 1 ~ "workday",
                                          TRUE ~ "weekend"),
         ) %>%
  select(
    date = dteday,
    season,
    year = yr,
    holiday,
    workingday = workingday,
    day_of_week = weekday,
    weather_type = weathersit,
    temp,
    feels_like = atemp,
    humidity = hum,
    wind_speed = windspeed,
    casual,
    registered
  ) %>%
  mutate(
    year = year + 2011,
    holiday = if_else(holiday == 1, "Y", "N"),
    season = c("W", "S", "U", "F")[season],
    temp = temp * (39 + 8) - 8,
    feels_like = feels_like * (50 + 16) - 16,
    wind_speed = wind_speed * 67
    ) %>% 
  pivot_longer(c(casual, registered),
               names_to = "rider_type",
               values_to = "rides") %>% 
  relocate(date, rider_type, rides) %>% 
  mutate(across(c(season, year, holiday, workingday, day_of_week, weather_type, rider_type), as.factor))



pin_write(
  board = board,
  x = daily_rides,
  name = "data202_bikeshare_day_simple_csv",
  type = "csv",
  title = "Capital Bikeshare data, day-level, simplified"
)

pin_write(
  board = board,
  x = daily_rides_bytype,
  name = "data202_bikeshare_day_by_type_csv",
  type = "csv",
  title = "Capital Bikeshare data, day-level, by rider type"
)

#pin_browse(board, "data202_bikeshare_day_simple_csv")
write_csv(daily_rides, get_out_filename("day_simple.csv", kind = 'bikeshare'))
write_csv(daily_rides_bytype, paste0(get_out_dir('bikeshare'), "day_by_type.csv"))
```

## datasaurus

```{r}
library(datasauRus)
write_csv(datasaurus_dozen, paste0(get_out_dir('datasaurus'), 'datasaurus.csv'))
```


## openintro loans (vis-numerical)

```{r}
openxlsx::write.xlsx(
  openintro::loans_full_schema,
  get_out_filename("openintro_loans_full_schema.xlsx")
)
  
```

