---
title: "Midterm Project"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: false
---

## **Midterm Project**: replicate and critique a visual

For this project you will pick some existing data science work (a blog post, report, research paper, etc.) and replicate a visual from it.

The project will explore the intersection between three things:

* The data
* The visualization
* The story that the visualization tells about the data (and, indirectly, about the world)

The three components to this project involve each of these three things:

* **Data**: Obtain some real-world dataset. Trace where it came from and how it's structured. Load it and process it *using the data science toolkit we're studying* to a form that's appropriate for making the visualization.
* **Visualization**: Replicate (re-create) a visualization that someone else already made based on that data. Evaluate some of the choices and assumptions that were made in the visualization process: in what ways does the visualization faithfully represent the data (or not)? What sort of stories does the chosen visualization amplify?
* **Story**: Consider the story that the original source told using the visualization. Is that story accurate? complete? clearly articulated? How did choices in the data collection, preparation, and visualization affect the storytelling? Are there other stories that the data might also be telling?

This project addresses our course-level learning objectives in this way:

* **Technical skills**: manipulating data, constructing visualizations, and creating reports.
* **Communication**: analyzing choices made in visualization and text with respect to how it tells a story about data. Proposing and implementing changes to improve the clarity of communication.
* **Ethics and Critical Thinking**: identify potential ethical questions (e.g., of transparency, diversity, etc.) that emerge in the process of obtaining, manipulating, and communicating with data.

### How to pick a plot?

You can pick one of these approaches:

- **Organization-centered**: Pick an organization that you're interested in (company, NGO, government agency, sports team, hospital, school, scientific community, etc.) and find some graphic that is helpful for them as they make decisions.
- **Issue-centered**: Pick an issue that's important to you. Find a news article or opinion piece about that issue, ideally one that you *disagree* with, and try to replicate a visual that they’d use to support their claims.
 
#### Your plot

- Should make an interesting *claim*.
  - Shouldn't just be *about* something (e.g., "number of wins by each athlete")
  - Most interesting claims are about *relationships* (e.g,. "the highest paid athletes don't necessarily win more")
- Should involve **more than 2 variables**.
  - Ideally they have to come from 2 separate data sources that you have to bring together.
- Should have some room for improvement, i.e., you'd be interested in trying a different way of presenting the data.

If you are really stuck, I can simply assign something to do, but I’m hoping to avoid that.

#### Your data

- Should come from a reputable source.
  - If you use an aggregation site like OurWorldInData, try to track down where *they* got the data.
- Should require at least a little bit of wrangling (beware of sites where you can download *exactly* the data for a specific plot)

There should be something interesting about the process of getting to the data frame that you plot. For example, you can focus on wrangling and manipulating the data, or you can focus on analyzing and critiquing the data collection process.


### Report

**Start with [this template Rmd file](project/datavis.Rmd)**. It includes a suggested outline for your report, which you can also view in this [rendered version](project/datavis.html).

Your report should be:

- *understandable by itself*: a reader should not need to see your discussion posts or prior submissions.
- *reproducible* -- if a new version of the data becomes available, anyone should be able to re-run your code and get an updated plot. Things to avoid:
  - paths that only work on your computer
  - making modifications to your raw data (e.g., editing it in Excel)
  - hard-coding row numbers or other things that are likely to change
- *understandable without the code*: a reader should be able to skip over all of the code and understand all of the results.

At least one of your visuals (either the original or alternative design) should be high quality, with effort spent getting the details right.



### Report Notes

- Clean up messy outputs. e.g., use `message = FALSE` in the chunk header or `show_col_types = FALSE` for `read_csv` (the main culprit).
- Write succinctly. Bulleted lists are fine when they're clear.
- Use ordinary text formatting (not headings, blockquotes, etc.) for ordinary prose. Reserve headings and block quotes for headings and quotes.
- Format your code cleanly. If lazy, select the code and click "Reformat Code" on the Code menu. (Make sure you save first.)
- Read through the report before submitting. Check that code doesn't run into the margin, figures show correctly, you don't have placeholder text, the headings make sense, etc.

Example chunk with some helpful flags:

<!-- https://bookdown.org/yihui/rmarkdown-cookbook/verbatim-code-chunks.html -->
`````
```{r chunk-name, message = FALSE, fig.height=10, fig.width=10, comment = ""}`r ''`

```
`````

**Academic Integrity**: Any code that you take from elsewhere **must** be *very clearly documented*. If you find a plot and it has R code already, I advise against looking at it, and possibly even finding a different plot. Code using a different toolkit (e.g., Python) is probably okay.

### Presentation

To practice making data-driven arguments, this project includes a brief presentation, done on VoiceThread.

Keep it short and simple. The slides should be as follows:

1. Original Plot and Claim
2. Data (where'd you get it, anything interesting about it or what you had to do with it)
3. Replication
4. Alternative 1: what did you change? why?
5. Alternative 2: (same)
6. Summary: one or two take-aways

Use a presentation tool like Google Slides or PowerPoint.

Use voice comments to narrate. Each team member should make at least one comment.

### Midterm Project Milestones

Milestones are due along with the corresponding week's homework.

- **Week 6**: Initial proposal.
  - Submit an HTML file (knitted from an `Rmd`) including the following information:
    - A screenshot of the visualization you propose to reproduce
    - A citation to an article that uses that visualization to make a claim (e.g., a complete URL)
    - A succinct statement of that claim
    - A potential source for the data
    - An initial description of the structure of that data (what rows and columns it has)
  - Regarding data:
    - If you are having trouble getting data, the course staff can be of help--but consider alternatives where you can get the data.
    - The data should require *some* wrangling. "Download data for this chart" links are red flags that you may be getting already-wrangled data.
- **Week 8**: Rough-draft replication.
  - Fill in the "Overview" and "Data" sections in `datavis.Rmd` (see the template link above)
  - The code in "Wrangling" doesn't need to be complete yet.
  - See submission instructions below.
  - Email the instructional staff, or ask on Ed, for what help you'll need!
- **Week 9**: Refinements
  - Have a complete replication of the original visualization
  - Have concrete ideas about alternative designs
  - Report should be complete through part 1 of Alternative Designs
- **Week 10**: *either* Final write-up *or* Presentation due
- **Week 11**: all parts due
  
### Submission instructions

- If your dataset is *less than 10 MB*: submit a **`.zip` file** with your entire project folder.
- Otherwise: submit just the HTML (and make sure the instructions are *very clear* about how to get the data)
  - Keep "Code Download" on so we can see your `Rmd`.
  

<!-- * **Week 2**: Propose 2 or 3 potential options that interest you, and write why you find them interesting. The course staff will help you determine what's feasible. -->
<!-- * **Week 3**: Pick a specific visualization to recreate and identify concrete steps towards obtaining the data. -->
<!-- * **Week 4**: Create a rough-draft visualization, including brief notes on how the data were obtained and story was originally told using that data. We will workshop some visualizations in class. -->
<!-- * **Week 5**: Provide feedback to other students. -->
<!-- * **Week 6**: Final visual, plus your critique of the original article and some follow-up questions. -->

### Helpful Resources

* See the [Course Notes](notes/), especially for visualization tweaks.
* [Some questions to ask if you're working with data that you didn't collect yourself](http://bit.ly/quaesita_notyours).


### Shared Projects

RStudio has a feature called Shared Projects that many teams will find helpful. But there's a bug involving uploading files to shared projects: only one person ends up able to read the file.

To fix it, the person who **can** read the file should run the following code chunk. (Change the file name, of course.) After the code chunk runs successfully, you should remove it from your report.

```r
fix_file <- function(filename) { 
  contents <- readr::read_file_raw(filename)
  if (length(contents) == 0) stop("Refusing to fix a file that seems empty.")
  unlink(filename)
  readr::write_file(contents, filename)
}
fix_file("data/YOUR-FILE-NAME.csv")
```

Note: be careful doing this for `Rmd` files: *make sure everyone has the Rmd file closed first*.
