---
title: "Assignment Management"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# remotes::install_github("rundel/ghclass")
library(ghclass)
library(tidyverse)
library(glue)
library(reticulate)
```

```{r}
org_outside_collaborators <- function(org) {
  ghclass:::ghclass_api_v3_req(endpoint = "GET /orgs/:org/outside_collaborators", org = org) %>%
    purrr::map_chr("login")
}
```


```{r}
ghorg <- "Calvin-DS202-FA20"
```

```{r}
roster <- read_csv("../roster.csv", col_types = cols(
  .default = col_character()
)) %>% janitor::clean_names()
nrow(roster)
stopifnot(
  0 == length(org_members(ghorg) %>% setdiff(org_admins(ghorg)) %>% setdiff(roster$github))
)
```

# Set up assignment templates

```{r}
org_sitrep(ghorg)
```

# Assign Teams


```{r assign-teams}
team_seeds <- tribble(
  ~assignment, ~seed,
  "lab04", 0
)
```


```{r assign-teams}
assignment <- "lab04"
seed <- 0
roster_withteams <- roster %>%
  { withr::with_seed(seed, slice_sample(., prop=1)) } %>% 
  group_by(cohort) %>% 
  mutate(
    team = glue("{assignment}-{cohort}{if_else((row_number() - 1) / n() < .5, 1, 2)}")
  ) %>%
  ungroup()
roster_withteams


danish_team <- roster_withteams %>% filter(str_detect(student_name, "Danish")) %>% pull(team)
if (3 != roster_withteams %>% filter(team == danish_team) %>% nrow()) {
  stop("Danish should always be on a team of 3.")
}
```

Run this to copy team membership to clipboard. Paste into Excel and copy back out again for easy formatting as HTML table.

```{r copy-team-membership, eval=FALSE}
roster_withteams %>%
  select(Name = preferred_full_name, Team = team) %>%
  arrange(Team) %>% 
  clipr::write_clip()
```

```{r}
roster_withteams %>% filter(cohort == "H") %>% select(student_name, preferred_email, cohort)
```


```{r team-member-count}
roster_withteams %>% count(team)
```

# Create Assignment

```{r}
createAssignment <- function(assignmentTemplatePath, use_template_repo = TRUE) {
  assignmentName <- stringr::str_match(assignmentTemplatePath, r"{\w+/([a-z0-9]+)}")[,2]
  message(glue("Creating assignment {assignmentName}"))
  repoName <- paste0(assignmentName, "-template")
  repo_create(ghorg, repoName, gitignore_template = "")
  
  # If we have big data files, can't use template repos.
  if (use_template_repo)
    repo_set_template(paste0(ghorg, "/", repoName))
  
  message("Pushing local repo")
  system2("./make-repo.sh", c(repoName, assignmentTemplatePath))
  message(glue("Pushed repo to https:://github.com/{ghorg}/{repoName}"))
}
```

```{r, eval=FALSE}
createAssignment("lab/lab04-covid/")
```

```python
import subprocess, pathlib
file_list = subprocess.run(
  ["git", "ls-files", "-z"], stdout=subprocess.PIPE, cwd=str(pathlib.Path("hw/hw03-agg"))
).stdout.split(b'\0')[:-1]
for f in file_list:
  f = f.decode('utf-8')
  if "solution" in f:
    continue
  print(f)
  
```


# Push repo to students


```{r eval=FALSE}
lab04_repodata <- roster_withteams %>%
  select(github, team) %>% 
  bind_rows(tibble(github = c("kcarnold", "kimyejae"), team = "lab04-staff")) %>% 
  mutate(
    repo_base = team,
    repo_full = paste0(ghorg, "/", repo_base)
  )

lab04_repodata %>% 
  {
    org_create_assignment(
      org = ghorg,
      user = .$github,
      repo = .$repo_base,
      team = .$team,
      source_repo = paste0(ghorg, "/", "lab04-template")
    )
  }
# org_create_assignment(
#   org = ghorg,
#   user = users,
#   repo = paste0("hw03-", roster$github_username),
#   source_repo = paste0(ghorg, "/", "hw03-template")
# )
```

```{r}
repo_delete(lab04_repodata$repo_full)
```


```{r}
repo_add_team(
  repo = lab04_repodata$repo_full,
  team = lab04_repodata$team
)
```


# Harvest Student Work

```{r message=FALSE, eval=FALSE}
assignmentName <- "hw02"

assignments_root <- "../fa20/"
all_repos <- org_repos(ghorg)
assignment_path <- file.path(assignments_root, assignmentName)
roster %>% 
  mutate(
    repo_name = glue("{ghorg}/{assignmentName}-{github}"),
    repo_url = glue("https://github.com/{repo_name}"),
    repo_path = fs::path_expand(file.path(assignment_path, glue("{assignmentName}-{preferred_full_name}")))
  ) %>%
  rowwise() %>% 
  mutate(status = {
    if (file.exists(repo_path)) {
      # Update (pull)
      local_repo_pull(repo_path)
    } else if (repo_name %in% all_repos) {
      # Clone
      gert::git_clone(url = repo_url, path = repo_path, 
        branch = "master", verbose = TRUE)
    } else {
      message(paste0("Missing ", assignmentName, " for ", preferred_name))
    }
    "ok"
  })
```

```{r results='asis'}
assignmentName <- "hw02"

students %>% 
  mutate(
    repo_name = glue("{ghorg}/{assignmentName}-{github_username}"),
    repo_url = glue("https://github.com/{repo_name}"),
    md = glue("* [{name}]({repo_url})")
  ) %>% pull(md) %>% cat(sep = "\n")
```



```{r message=FALSE, eval=FALSE}
# Clone or update repos for all students
repos_for_assignment <- students %>% purrr::map_chr(function(student) {
  student_repo_name <- paste0(assignmentName, "-", student)
  student_repo_fullname <- paste0(ghorg, "/", student_repo_name)
  repo_path <- file.path(assignment_path, student_repo_name)
  if (file.exists(repo_path)) {
    # Update (pull)
    local_repo_pull(repo_path)
  } else if (student_repo_fullname %in% all_repos) {
    # Clone
    local_repo_clone(
      repo = student_repo_fullname,
      local_path = assignment_path,
      verbose = TRUE
    )
  } else {
    message(paste0("Missing ", assignmentName, " for ", student))
    return(NA)
  }
  return(student_repo_fullname)
})
```



```{r}
#repo_watching()
```

