---
title: "Slides 5.2: Wrangling Example"
icon: "file-slides"
format:
  revealjs:
    scrollable: true
    revealjs-plugins:
      - "fix-plotly-size"
execute: 
  echo: true
include-in-header: 
  text: |
    <style>
      .mchoice li { list-style-type: upper-alpha; }
      .midi table, table.dataframe, .cell-output table {
        font-size: .6em;
      }
      .cell-output {
        font-size: .75em;
      }
      .smaller table {
        font-size: .5em;
      }
      .copilot::before {
        content: "GitHub Copilot says:";
        font-size: .5em;
      }
      /* grey text, light background */
      .copilot {
        color: #555;
        background-color: #eee;
        padding: 0.5em;
        border-radius: 0.5em;
      }
      .exercise {
        color: #555;
        background-color: #eee;
        padding: 0.5em;
        border-radius: 0.5em;
        margin: 0.25em 0;
      }
      .exercise::before {
        display: inline-block;
        text-rendering: auto;
        -webkit-font-smoothing: antialiased;
        font: var(--fa-font-solid);
        content: "\f303";
        font-size: .5em;
        position: absolute;
      }
    </style>
---

```{python}
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.io as pio
pd.options.plotting.backend = "plotly"
pio.templates.default = "plotly_white"
```

# Review: pandas and the grammar of data

```{python}
colleges = pd.read_csv("https://calvin-data-science.github.io/data202/data/college_scorecard.csv")
colleges.info()
```

## select columns

::: columns
::: {.column width="50%"}
```{python}
colleges[['name', 'undergrads']]
```

Documentation on [indexing](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html)
:::
::: {.column width="50%"}
Getting a single column as a `Series`:

```{python}
colleges['name']
```
:::
:::

## select rows (`query`)

```{python}
colleges.query("state == 'AK'")
```

Documentation: [pandas.DataFrame.query](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.query.html)

## top and bottom

::: {.columns}
::: {.column width="50%"}
```{python}
colleges.head()
```
:::
::: {.column width="50%"}
```{python}
colleges.tail()
```
:::
:::

## arrange rows (`sort_values`)

```{python}
colleges.sort_values("undergrads").head()
```

```{python}
colleges.sort_values("undergrads", ascending=False).head()
```

Documentation: [pandas.DataFrame.sort_values](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_values.html)

## counting

```{python}
colleges.groupby("state", as_index=False).size()
```

## grouping / summarizing (general)

```{python}
colleges.groupby("state", as_index=False).agg(
  count=('undergrads', 'count'),
  mean_undergrads=('undergrads', 'mean'),
  max_undergrads=('undergrads', 'max')
)
```


## random sampling

::: columns
::: {.column width="50%"}

Shuffle rows:

```{python}
colleges.sample(frac=1.0).head()
```
:::
::: {.column width="50%"}
Select random rows:

```{python}
colleges.sample(n=5)
```
:::
:::

## Deriving new columns

```{python}
colleges['named_university'] = colleges['name'].str.contains('University')
colleges.groupby('named_university', as_index=False).agg(
  mean_undergrads=('undergrads', 'mean'),
  max_undergrads=('undergrads', 'max')
)
```

## "Broadcast" operations

Apply an operation to an entire column at a time.

```{python}
colleges['undergrads'] / 1000
```

```{python}
pd.isna(colleges['undergrads'])
```

## Pairs of columns

When broadcasting with a pair of columns, the operation is applied element-wise.

```{python}
colleges['city'].str.cat(colleges['state'], sep=', ')
```

## Deriving new columns, advanced

```{python}
def classify_name(school_name):
    school_name = school_name.lower()
    if 'university' in school_name:
        return 'university'
    elif 'college' in school_name:
        return 'college'
    else:
        return 'other'
colleges['name_type'] = colleges['name'].apply(classify_name)
colleges.groupby('name_type', as_index=False).agg(
  mean_undergrads=('undergrads', 'mean'),
  max_undergrads=('undergrads', 'max')
)
```

Note: this is slower because it runs unoptimized Python code for each row. First, make it correct, then make it fast (e.g., [`np.select`](https://numpy.org/doc/stable/reference/generated/numpy.select.html)).


# Wrangling example

## Data: Hotel bookings

- Data from two hotels: one resort and one city hotel
- Observations: Each row represents a hotel booking
- Goal for original data collection: Development of prediction models to classify a hotel booking's likelihood to be cancelled ([Antonia et al., 2019](https://www.sciencedirect.com/science/article/pii/S2352340918315191#bib5))

## Data download {.smaller}

```{python}
hotels_url = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-11/hotels.csv"
import pathlib, requests

cache_filename = pathlib.Path('data/hotels.csv')
if not cache_filename.exists():
    cache_filename.parent.mkdir(parents=True, exist_ok=True)
    cache_filename.write_bytes(requests.get(hotels_url).content)
```

```{python}
hotels = pd.read_csv(cache_filename)
hotels.head()
```

::: aside

Source: [TidyTuesday](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-02-11/readme.md)

:::

## What are some of the variables and their data types?

```{python}
hotels.info()
```

```{python}
hotels.describe()
```

## How many different hotels are there?

## Which hotel has more bookings?

## Which hotel has longer stays?

Add `stays_in_week_nights` and `stays_in_weekend_nights` to get total length of stay.

## Which market segment is most common?

## How much in advance are bookings made?

## Which market segments book most in advance?

## How long are typical stays for each hotel?

